# Generated by Django 4.2 on 2024-05-17 17:04

from django.db import migrations, models
import django.utils.timezone
import squarelet.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0034_auto_20240304_1245"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectionResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the resource", verbose_name="name"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Who contributed the resource", verbose_name="source"
                    ),
                ),
                (
                    "category",
                    models.IntegerField(
                        choices=[
                            (0, "Investigating Candidates"),
                            (1, "Polling"),
                            (2, "Data"),
                            (3, "Voter Guide"),
                            (4, "Election Night Ops"),
                            (5, "Misinfo / Deepfakes"),
                            (6, "Violence"),
                            (7, "Coverage Training / Coordination"),
                            (8, "Content Sharing"),
                            (9, "Newsletters"),
                        ],
                        help_text="The category of the resource",
                        verbose_name="category",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="A brief description of the resource",
                        verbose_name="description",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="The URL where the resource can be accessed",
                        verbose_name="url",
                    ),
                ),
                (
                    "created_at",
                    squarelet.core.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this resource was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    squarelet.core.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this resource was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Organizations which are a member of this organization may access this resource",
                        limit_choices_to={"individual": False},
                        related_name="resources",
                        to="organizations.organization",
                        verbose_name="members",
                    ),
                ),
                (
                    "subtypes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The organization subtypes which may access this resource",
                        related_name="resources",
                        to="organizations.organizationsubtype",
                        verbose_name="subtypes",
                    ),
                ),
            ],
        ),
    ]
