# Generated by Django 4.2 on 2024-05-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="electionresource",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Should this resource be shown",
                verbose_name="active",
            ),
        ),
    ]
