name: ${COMPOSE_PROJECT_NAME:-squarelet}

volumes:
  postgres15_data_local: {}
  postgres15_backup_local: {}

services:
  squarelet_nginx:
    image: nginx:latest
    depends_on:
      - squarelet_mailhog
    volumes:
      - ./compose/local/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    networks:
      default:
        aliases:
          - dev.mailhog.com
          - dev.squarelet.com
          - api.dev.documentcloud.org
          - www.dev.documentcloud.org
          - dev.muckrock.com
          - dev.foiamachine.org

  squarelet_mailhog:
    image: mailhog/mailhog:v1.0.0
    environment:
      - MH_API_BIND_ADDR=0.0.0.0:80
      - MH_UI_BIND_ADDR=0.0.0.0:80
    user: root
    networks:
      default:
        aliases:
          - internal.dev.mailhog.com

  squarelet_django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: squarelet_local_django
    depends_on:
      - squarelet_postgres
      - squarelet_mailhog
      - squarelet_nginx
    volumes:
      - .:/app
      - ~/.netrc:/root/.netrc
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    command: /start
    networks:
      default:
        aliases:
          - internal.dev.squarelet.com
          - internal.dev.presspass.com

  squarelet_vite:
    build:
      context: .
      dockerfile: ./compose/local/vite.Dockerfile
    image: squarelet_local_vite
    restart: always
    ports:
      - "4200:4200"
      # - "5173:5173"
    command: "npm run dev"
    volumes:
      - ".:/app"
      - "/app/node_modules" # prevent overwrite
    networks:
      default:
        aliases:
          - internal.dev.squarelet.com
          - internal.dev.presspass.com

  squarelet_postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: squarelet_production_postgres15
    volumes:
      - postgres15_data_local:/var/lib/postgresql/data
      - postgres15_backup_local:/backups
    env_file:
      - ./.envs/.local/.postgres

  squarelet_redis:
    image: redis:3.2

  squarelet_celeryworker:
    <<: *django
    image: squarelet_local_celeryworker
    depends_on:
      - squarelet_redis
      - squarelet_postgres
      - squarelet_mailhog
    command: /start-celeryworker
    networks:
      default:
        aliases: []

  squarelet_celerybeat:
    <<: *django
    image: squarelet_local_celerybeat
    depends_on:
      - squarelet_redis
      - squarelet_postgres
      - squarelet_mailhog
    command: /start-celerybeat
    networks:
      default:
        aliases: []

networks:
  default:
    name: "squarelet_default"
