# Generated by Django 5.2.11 on 2026-02-22 20:33

# Django
import django.contrib.postgres.fields.citext
import django.contrib.postgres.operations
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

# Third Party
import sorl.thumbnail.fields

# Squarelet
import squarelet.core.fields
import squarelet.core.mixins
import squarelet.users.managers
import squarelet.users.models
import squarelet.users.validators


class Migration(migrations.Migration):

    replaces = [
        ("users", "0001_initial"),
        ("users", "0002_auto_20190919_1601"),
        ("users", "0003_auto_20191024_1643"),
        ("users", "0004_auto_20191119_1416"),
        ("users", "0005_auto_20200407_1118"),
        ("users", "0006_alter_user_source"),
        ("users", "0007_alter_user_source"),
        ("users", "0008_user_bio"),
        ("users", "0009_alter_user_source"),
        ("users", "0010_case_insenstive_collation"),
        ("users", "0011_alter_user_email_alter_user_username"),
    ]

    initial = True

    dependencies = [
        ("auth", "0009_alter_user_last_name_max_length"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        django.contrib.postgres.operations.CreateCollation(
            name="case_insensitive",
            locale="und-u-ks-level2",
            provider="icu",
            deterministic=False,
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The user's full name",
                        max_length=255,
                        verbose_name="name of user",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_collation="case_insensitive",
                        help_text="The user's email address",
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="email",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_collation="case_insensitive",
                        error_messages={
                            "unqiue": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and ./-/_ only.  May only be changed once.",
                        max_length=150,
                        unique=True,
                        validators=[squarelet.users.validators.UsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                (
                    "avatar",
                    sorl.thumbnail.fields.ImageField(
                        blank=True,
                        help_text="An image to represent the user",
                        max_length=255,
                        upload_to=squarelet.users.models.user_file_path,
                        verbose_name="avatar",
                    ),
                ),
                (
                    "can_change_username",
                    models.BooleanField(
                        default=True,
                        help_text="Keeps track of whether or not the user has used their one username change",
                        verbose_name="can change username",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_agency",
                    models.BooleanField(
                        default=False,
                        help_text="This is an account used for allowing agencies to log in to the site",
                        verbose_name="agency user",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("muckrock", "MuckRock"),
                            ("documentcloud", "DocumentCloud"),
                            ("foiamachine", "FOIA Machine"),
                            ("squarelet", "Squarelet"),
                            ("biglocalnews", "Big Local News"),
                            ("agendawatch", "Agenda Watch"),
                        ],
                        default="squarelet",
                        help_text="Which service did this user originally sign up for?",
                        max_length=13,
                        verbose_name="source",
                    ),
                ),
                (
                    "email_failed",
                    models.BooleanField(
                        default=False,
                        help_text="Has an email we sent to this user's email address failed?",
                        verbose_name="email failed",
                    ),
                ),
                (
                    "created_at",
                    squarelet.core.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this user was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    squarelet.core.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this user was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "use_autologin",
                    models.BooleanField(
                        default=True,
                        help_text="Links you receive in emails from us will contain a token to automatically log you in",
                        verbose_name="use autologin",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "individual_organization",
                    models.OneToOneField(
                        editable=False,
                        help_text="This is both the UUID for the user, as well as a foreign key to the corresponding individual organization, which has the same UUID. This is used to uniquely identify the user across services.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                        to_field="uuid",
                        verbose_name="individual organization",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Public bio for the user, in Markdown",
                        verbose_name="bio",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "ordering": ("username",),
            },
            bases=(squarelet.core.mixins.AvatarMixin, models.Model),
            managers=[
                ("objects", squarelet.users.managers.UserManager()),
            ],
        ),
    ]
