# Generated by Django 2.1.7 on 2019-09-19 20:01

import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sorl.thumbnail.fields
import squarelet.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='An image to represent the user', max_length=255, upload_to='avatars', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=squarelet.core.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, help_text='When this user was created', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(help_text="The user's email address", max_length=254, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='individual_organization',
            field=models.OneToOneField(editable=False, help_text='This is both the UUID for the user, as well as a foreign key to the corresponding individual organization, which has the same UUID. This is used to uniquely identify the user across services.', on_delete=django.db.models.deletion.PROTECT, to='organizations.Organization', to_field='uuid', verbose_name='individual organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text="The user's full name", max_length=255, verbose_name='name of user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='source',
            field=models.CharField(choices=[('muckrock', 'MuckRock'), ('documentcloud', 'DocumentCloud'), ('foiamachine', 'FOIA Machine'), ('quackbot', 'QuackBot'), ('squarelet', 'Squarelet')], default='squarelet', help_text='Which service did this user originally sign up for?', max_length=11, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=squarelet.core.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, help_text='When this user was last updated', verbose_name='updated at'),
        ),
    ]
