# Generated by Django 2.0.6 on 2018-07-31 20:36

# Django
import django.contrib.postgres.fields.citext
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations

# Squarelet
import squarelet.users.validators


class Migration(migrations.Migration):

    dependencies = [("users", "0001_initial")]

    operations = [
        CITextExtension(),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=django.contrib.postgres.fields.citext.CIEmailField(
                max_length=254, unique=True, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=django.contrib.postgres.fields.citext.CICharField(
                error_messages={"unqiue": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and ./+/-/_ only",
                max_length=150,
                unique=True,
                validators=[squarelet.users.validators.UsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
