# Generated by Django 2.0.6 on 2018-08-01 17:20

import django.contrib.postgres.fields.citext
from django.db import migrations
import sorl.thumbnail.fields
import squarelet.users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180731_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=django.contrib.postgres.fields.citext.CICharField(error_messages={'unqiue': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and ./-/_ only', max_length=150, unique=True, validators=[squarelet.users.validators.UsernameValidator()], verbose_name='username'),
        ),
    ]
