# Generated by Django 2.1.7 on 2019-10-24 20:43

from django.db import migrations
import sorl.thumbnail.fields
import squarelet.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190919_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='An image to represent the user', max_length=255, upload_to=squarelet.users.models.user_file_path, verbose_name='avatar'),
        ),
    ]
