# Generated by Django 2.0.6 on 2018-08-17 17:26

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180801_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_change_username',
            field=models.BooleanField(default=True, help_text='Keeps track of whether or not the user has used their one username change', verbose_name='can change username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='avatars', verbose_name='avatar'),
        ),
    ]
