# Generated by Django 2.0.6 on 2018-08-21 14:30

import django.contrib.postgres.fields.citext
from django.db import migrations
import squarelet.users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180817_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=django.contrib.postgres.fields.citext.CICharField(error_messages={'unqiue': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and ./-/_ only.  May only be changed once.', max_length=150, unique=True, validators=[squarelet.users.validators.UsernameValidator()], verbose_name='username'),
        ),
    ]
