# Generated by Django 3.2.11 on 2022-06-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200407_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='source',
            field=models.CharField(choices=[('muckrock', 'MuckRock'), ('documentcloud', 'DocumentCloud'), ('foiamachine', 'FOIA Machine'), ('quackbot', 'QuackBot'), ('squarelet', 'Squarelet'), ('presspass', 'PressPass'), ('biglocalnews', 'Big Local News')], default='squarelet', help_text='Which service did this user originally sign up for?', max_length=13, verbose_name='source'),
        ),
    ]
