# Generated by Django 2.0.6 on 2019-02-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180821_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='use_autologin',
            field=models.BooleanField(default=True, help_text='Links you receive in emails from us will contain a token to automatically log you in', verbose_name='use autologin'),
        ),
    ]
