# Generated by Django 3.2.11 on 2022-11-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='source',
            field=models.CharField(choices=[('muckrock', 'MuckRock'), ('documentcloud', 'DocumentCloud'), ('foiamachine', 'FOIA Machine'), ('squarelet', 'Squarelet'), ('biglocalnews', 'Big Local News')], default='squarelet', help_text='Which service did this user originally sign up for?', max_length=13, verbose_name='source'),
        ),
    ]
