# Generated by Django 3.2.11 on 2023-01-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Public bio for the user, in Markdown', verbose_name='bio'),
        ),
    ]
