# Generated by Django 2.1.7 on 2019-02-22 16:23

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(max_length=254, null=True, unique=True, verbose_name='email'),
        ),
    ]
