# Generated by Django 2.1.7 on 2019-02-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190222_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_failed',
            field=models.BooleanField(default=False, help_text="Has an email we sent to this user's email address failed?", verbose_name='email failed'),
        ),
    ]
