# Generated by Django 2.1.7 on 2019-03-07 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_email_failed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='organizations.Organization'),
        ),
    ]
