# Generated by Django 4.2 on 2023-06-26 20:19

from django.db import migrations, models
import squarelet.users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_case_insenstive_collation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_collation="case_insensitive",
                help_text="The user's email address",
                max_length=254,
                null=True,
                unique=True,
                verbose_name="email",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                db_collation="case_insensitive",
                error_messages={"unqiue": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and ./-/_ only.  May only be changed once.",
                max_length=150,
                unique=True,
                validators=[squarelet.users.validators.UsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
