# Generated by Django 4.2 on 2024-11-01 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import squarelet.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("oidc_provider", "0026_client_multiple_response_types"),
        ("users", "0011_alter_user_email_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="source",
            field=models.CharField(
                choices=[
                    ("muckrock", "MuckRock"),
                    ("documentcloud", "DocumentCloud"),
                    ("foiamachine", "FOIA Machine"),
                    ("squarelet", "Squarelet"),
                    ("election-hub", "Election Hub"),
                    ("biglocalnews", "Big Local News"),
                    ("agendawatch", "Agenda Watch"),
                ],
                default="squarelet",
                help_text="Which service did this user originally sign up for?",
                max_length=13,
                verbose_name="source",
            ),
        ),
        migrations.CreateModel(
            name="LoginLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metadata", models.JSONField(default=dict, verbose_name="metadata")),
                (
                    "created_at",
                    squarelet.core.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created at",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logins",
                        to="oidc_provider.client",
                        verbose_name="client",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logins",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
    ]
