# Generated by Django 4.2 on 2025-01-10 18:49

# Django
from django.db import migrations


def make_github(apps, schema_editor):
    """Change github_app to github"""
    SocialAccount = apps.get_model("socialaccount", "SocialAccount")
    SocialApp = apps.get_model("socialaccount", "SocialApp")

    SocialAccount.objects.filter(provider="github_app").update(provider="github")
    SocialApp.objects.filter(provider="github_app").update(provider="github")


def make_github_app(apps, schema_editor):
    """Change github to github_app"""
    SocialAccount = apps.get_model("socialaccount", "SocialAccount")
    SocialApp = apps.get_model("socialaccount", "SocialApp")

    SocialAccount.objects.filter(provider="github").update(provider="github_app")
    SocialApp.objects.filter(provider="github").update(provider="github_app")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_user_source_loginlog"),
    ]

    operations = [migrations.RunPython(make_github, make_github_app)]
