# Generated by Django 2.1.7 on 2019-03-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190307_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='individual_organization',
        ),
    ]
