# Generated by Django 4.2 on 2025-05-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_auto_20250110_1349"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_mfa_prompt",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
