# Generated by Django 2.1.7 on 2019-03-16 21:48

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190308_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(blank=True, max_length=255, upload_to='avatars', verbose_name='avatar'),
        ),
    ]
