# Generated by Django 5.2.12 on 2026-09-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_user_last_mfa_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="client_stats",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stats synced nightly from client services, keyed by client name",
                verbose_name="client stats",
            ),
        ),
    ]
