# Generated by Django 5.2.12 on 2026-09-22 18:42

import django.db.models.deletion
import django.utils.timezone
import squarelet.core.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_user_client_stats"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The script or tool using this token",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        editable=False,
                        max_length=16,
                        unique=True,
                        verbose_name="prefix",
                    ),
                ),
                (
                    "hashed_secret",
                    models.CharField(
                        editable=False, max_length=64, verbose_name="hashed secret"
                    ),
                ),
                (
                    "allow_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Tokens may only use the user's staff access when this is set",
                        verbose_name="allow staff access",
                    ),
                ),
                (
                    "expires_in",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (7, "1 week"),
                            (30, "1 month"),
                            (90, "3 months"),
                            (365, "1 year"),
                        ],
                        help_text="The lifetime chosen when the token was created; blank is never",
                        null=True,
                        verbose_name="expires in (days)",
                    ),
                ),
                (
                    "created_at",
                    squarelet.core.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created at",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last used at"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expires at"
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="revoked at"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
