# Generated by Django 2.0.6 on 2018-10-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='next_org_type',
            field=models.IntegerField(choices=[(0, 'Free'), (1, 'Pro'), (2, 'Basic'), (3, 'Plus')], default=2, help_text='Type to switch to at next billing cycle', verbose_name='next organization type'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
    ]
