# Generated by Django 2.0.6 on 2018-10-08 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_auto_20181006_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='receiptemail',
            old_name='org',
            new_name='organization',
        ),
        migrations.AlterField(
            model_name='organization',
            name='max_users',
            field=models.IntegerField(default=5, verbose_name='maximum users'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.IntegerField(choices=[(0, 'Free'), (1, 'Pro'), (2, 'Basic'), (3, 'Plus')], default=0, verbose_name='organization type'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organizations.Organization'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who accepted this invitation - NULL means it has not been accepted yet', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
