# Generated by Django 2.0.6 on 2018-10-23 19:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_auto_20181008_1847'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationMembership',
            new_name='Membership',
        ),
    ]
