# Generated by Django 2.1.7 on 2019-07-12 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import squarelet.core.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0004_auto_20190329_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', squarelet.core.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('reason', models.PositiveSmallIntegerField(choices=[(0, 'Created'), (1, 'Updated'), (2, 'Payment failed')])),
                ('from_max_users', models.IntegerField(blank=True, null=True, verbose_name='maximum users')),
                ('to_max_users', models.IntegerField(verbose_name='maximum users')),
                ('from_next_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.Plan')),
                ('from_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.Plan')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='organizations.Organization')),
                ('to_next_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.Plan')),
                ('to_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.Plan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
