# Generated by Django 2.0.6 on 2018-10-24 01:37

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20181023_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='slug'),
        ),
    ]
