# Generated by Django 2.1.7 on 2019-10-24 20:47

from django.db import migrations
import sorl.thumbnail.fields
import squarelet.organizations.models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20190919_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='An image to represent the organization', upload_to=squarelet.organizations.models.organization_file_path, verbose_name='avatar'),
        ),
    ]
