# Generated by Django 2.0.6 on 2018-10-25 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20181024_0137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('slug',)},
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='num_pages',
            new_name='number_pages',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='num_requests',
            new_name='number_requests',
        ),
    ]
