# Generated by Django 2.1.7 on 2019-11-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_auto_20191024_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='requires_updates',
            field=models.BooleanField(default=True, help_text='Specifies if this plan requires monthly updates, in order for client sites to restore montly consumable resources', verbose_name='requires updates'),
        ),
    ]
