# Generated by Django 2.0.6 on 2018-10-30 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_auto_20181025_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='next_org_type',
            new_name='next_plan',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='org_type',
            new_name='plan',
        ),
    ]
