# Generated by Django 2.0.6 on 2018-10-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_auto_20181030_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='next_plan',
            field=models.IntegerField(choices=[(0, 'Free'), (1, 'Pro'), (2, 'Basic'), (3, 'Plus')], default=2, help_text='Type to switch to at next billing cycle', verbose_name='next plan'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='plan',
            field=models.IntegerField(choices=[(0, 'Free'), (1, 'Pro'), (2, 'Basic'), (3, 'Plus')], default=0, verbose_name='plan'),
        ),
    ]
