# Generated by Django 2.1.7 on 2019-11-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_plan_requires_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='private_organizations',
            field=models.ManyToManyField(blank=True, help_text='For private plans, organizations which should have access to this plan', related_name='private_plans', to='organizations.Organization', verbose_name='private organizations'),
        ),
    ]
