# Generated by Django 2.0.6 on 2018-11-06 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import squarelet.core.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_auto_20181030_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='accepted_at'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='created_at',
            field=squarelet.core.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='request',
            field=models.BooleanField(default=False, help_text='Is this a request for an invitation from the user or an invitation to the user from an admin?', verbose_name='request'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uuid'),
        ),
    ]
