# Generated by Django 2.0.6 on 2019-01-30 14:34

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_auto_20181106_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='org_avatars', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='next_plan',
            field=models.IntegerField(choices=[(0, 'Free'), (1, 'Pro'), (2, 'Organization Basic'), (3, 'Organization Plus')], default=0, help_text='Type to switch to at next billing cycle', verbose_name='next plan'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='plan',
            field=models.IntegerField(choices=[(0, 'Free'), (1, 'Pro'), (2, 'Organization Basic'), (3, 'Organization Plus')], default=0, verbose_name='plan'),
        ),
    ]
