# Generated by Django 2.0.6 on 2018-12-21 20:02

# Django
import django.db.models.deletion
from django.db import migrations, models

# Third Party
import autoslug.fields


class Migration(migrations.Migration):

    dependencies = [("organizations", "0012_auto_20181219_1929")]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from="name",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "minimum_users",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="minimum users"
                    ),
                ),
                (
                    "base_price",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="base price"
                    ),
                ),
                (
                    "price_per_user",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="price per user"
                    ),
                ),
                (
                    "feature_level",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="feature level"
                    ),
                ),
                ("public", models.BooleanField(default=False, verbose_name="public")),
                (
                    "for_individuals",
                    models.BooleanField(
                        default=True,
                        help_text="Is this plan usable for individual organizations?",
                        verbose_name="for individuals",
                    ),
                ),
                (
                    "for_groups",
                    models.BooleanField(
                        default=True,
                        help_text="Is this plan usable for non-individual organizations?",
                        verbose_name="for groups",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="organization", name="plan"),
        migrations.RemoveField(model_name="organization", name="next_plan"),
        migrations.AddField(
            model_name="organization",
            name="next_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_organizations",
                to="organizations.Plan",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organizations",
                to="organizations.Plan",
                null=True,
            ),
        ),
    ]
