# Generated by Django 2.1.7 on 2019-12-20 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_auto_20191213_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationchangelog',
            name='to_next_plan',
            field=models.ForeignKey(blank=True, help_text="The organization's plan after the change occurred", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.Plan', verbose_name='to next plan'),
        ),
        migrations.AlterField(
            model_name='organizationchangelog',
            name='to_plan',
            field=models.ForeignKey(blank=True, help_text="The organization's plan after the change occurred", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.Plan', verbose_name='to plan'),
        ),
    ]
