# Generated by Django 2.0.6 on 2019-01-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_auto_20181221_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='annual',
            field=models.BooleanField(default=False, help_text='Invoice this plan annually instead of charging monthly', verbose_name='annual'),
        ),
    ]
