# Generated by Django 2.1.7 on 2020-01-13 21:34

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("organizations", "0013_auto_20191220_1437")]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_account",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "MuckRock"), (1, "PressPass")],
                        help_text="Which company's stripe account",
                        verbose_name="stripe account",
                    ),
                ),
                (
                    "customer_id",
                    models.CharField(
                        help_text="The customer's corresponding ID on stripe",
                        max_length=255,
                        unique=True,
                        verbose_name="customer id",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="organizations.Organization",
                        verbose_name="organization",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="plan", old_name="pay_to", new_name="stripe_account"
        ),
        migrations.AddField(
            model_name="charge",
            name="stripe_account",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "MuckRock"), (1, "PressPass")],
                default=0,
                help_text="Which company's stripe account is used for this charge",
                verbose_name="stripe account",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customer", unique_together={("organization", "stripe_account")}
        ),
    ]
