# Generated by Django 2.0.6 on 2019-01-03 16:21

# Django
from django.db import migrations

PLANS = [
    {
        "name": "Free",
        "slug": "free",
        "minimum_users": 1,
        "base_price": 0,
        "price_per_user": 0,
        "feature_level": 0,
        "public": True,
        "annual": False,
        "for_individuals": True,
        "for_groups": True,
    },
    {
        "name": "Professional",
        "slug": "professional",
        "minimum_users": 1,
        "base_price": 40,
        "price_per_user": 0,
        "feature_level": 1,
        "public": True,
        "annual": False,
        "for_individuals": True,
        "for_groups": False,
    },
    {
        "name": "Organization",
        "slug": "organization",
        "minimum_users": 5,
        "base_price": 100,
        "price_per_user": 10,
        "feature_level": 2,
        "public": True,
        "annual": False,
        "for_individuals": False,
        "for_groups": True,
    },
    {
        "name": "Organization Plus",
        "slug": "organization-plus",
        "minimum_users": 5,
        "base_price": 200,
        "price_per_user": 20,
        "feature_level": 2,
        "public": False,
        "annual": False,
        "for_individuals": False,
        "for_groups": True,
    },
    {
        "name": "Admin",
        "slug": "admin",
        "minimum_users": 1,
        "base_price": 0,
        "price_per_user": 0,
        "feature_level": 2,
        "public": False,
        "annual": False,
        "for_individuals": True,
        "for_groups": True,
    },
    {
        "name": "Beta",
        "slug": "beta",
        "minimum_users": 1,
        "base_price": 0,
        "price_per_user": 0,
        "feature_level": 1,
        "public": False,
        "annual": False,
        "for_individuals": True,
        "for_groups": False,
    },
    {
        "name": "Proxy",
        "slug": "proxy",
        "minimum_users": 1,
        "base_price": 0,
        "price_per_user": 0,
        "feature_level": 1,
        "public": False,
        "annual": False,
        "for_individuals": True,
        "for_groups": False,
    },
    {
        "name": "Manual Pay Organization",
        "slug": "manual-pay-organization",
        "minimum_users": 5,
        "base_price": 100,
        "price_per_user": 10,
        "feature_level": 2,
        "public": False,
        "annual": True,
        "for_individuals": False,
        "for_groups": True,
    },
]


def add_plans(apps, schema_editor):
    Plan = apps.get_model("organizations", "Plan")
    for plan in PLANS:
        Plan.objects.create(**plan)


def remove_plans(apps, schema_editor):
    Plan = apps.get_model("organizations", "Plan")
    Plan.objects.all().delete()


def migrate_plans(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    Plan = apps.get_model("organizations", "Plan")
    free = Plan.objects.get(slug="free")

    Organization.objects.update(plan=free, next_plan=free)


class Migration(migrations.Migration):

    dependencies = [("organizations", "0014_plan_annual")]

    operations = [
        migrations.RunPython(add_plans, remove_plans),
        migrations.RunPython(migrate_plans, migrations.RunPython.noop),
    ]
