# Generated by Django 2.1.7 on 2020-01-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_auto_20200113_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='stripe_account',
            field=models.PositiveSmallIntegerField(choices=[(0, 'MuckRock'), (1, 'PressPass')], default=0, help_text="Which company's stripe account is used for subscrpitions to this plan", verbose_name='stripe account'),
        ),
    ]
