# Generated by Django 2.0.6 on 2019-01-08 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_auto_20190103_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='next_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pending_organizations', to='organizations.Plan'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='organizations.Plan'),
        ),
    ]
