# Generated by Django 2.1.7 on 2020-01-13 21:38

# Django
from django.db import migrations


def create_customers(apps, schema_editor):
    """Switch from single plan to multi plan database model"""
    Organization = apps.get_model("organizations", "Organization")
    Customer = apps.get_model("organizations", "Customer")

    for organization in Organization.objects.exclude(customer_id=None):
        Customer.objects.create(
            organization=organization,
            stripe_account=0,  # MuckRock
            customer_id=organization.customer_id,
        )


class Migration(migrations.Migration):

    dependencies = [("organizations", "0015_auto_20200113_1636")]

    operations = [migrations.RunPython(create_customers, migrations.RunPython.noop)]
