# Generated by Django 2.0.6 on 2019-01-30 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_auto_20190130_1434'),
        ('organizations', '0016_auto_20190108_2057'),
    ]

    operations = [
    ]
