# Generated by Django 2.0.6 on 2019-01-10 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_auto_20190108_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(help_text='Amount in cents', verbose_name='amount')),
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('charge_id', models.CharField(max_length=255, verbose_name='charge_id')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='organizations.Organization')),
            ],
        ),
    ]
