# Generated by Django 2.0.6 on 2019-01-31 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_merge_20190130_2216'),
        ('organizations', '0017_charge'),
    ]

    operations = [
    ]
