# Generated by Django 2.1.7 on 2020-05-19 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_auto_20200302_1628'),
        ('organizations', '0017_auto_20200407_1118'),
    ]

    operations = [
    ]
