# Generated by Django 2.0.6 on 2019-02-01 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_merge_20190131_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charge',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='invitation',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='invitation',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='rejected at'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='charge_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='charge_id'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='organizations.Organization'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='accepted at'),
        ),
    ]
