# Generated by Django 2.1.7 on 2020-05-19 18:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_merge_20200519_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitlement',
            name='resources',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Allows clients to track metadata for the resources this entitlement grants', verbose_name='resources'),
        ),
    ]
