# Generated by Django 2.0.6 on 2019-02-01 18:30

# Django
import django.contrib.postgres.fields.citext
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("organizations", "0019_auto_20190201_0125")]

    operations = [
        CITextExtension(),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(
                max_length=255, unique=True, verbose_name="name"
            ),
        ),
    ]
