# Generated by Django 2.0.6 on 2019-02-01 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_auto_20190201_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='date_update',
            new_name='update_on',
        ),
    ]
