# Generated by Django 2.0.6 on 2019-02-04 20:20

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_auto_20190201_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptemail',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterUniqueTogether(
            name='receiptemail',
            unique_together={('organization', 'email')},
        ),
    ]
