# Generated by Django 2.1.7 on 2020-05-26 19:56

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0026_client_multiple_response_types'),
        ('organizations', '0021_auto_20200521_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitlement',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, help_text='A slug to identify the plan', populate_from='name', unique_with=('client',), verbose_name='slug'),
        ),
        migrations.AlterUniqueTogether(
            name='entitlement',
            unique_together={('slug', 'client'), ('name', 'client')},
        ),
    ]
