# Generated by Django 2.0.6 on 2019-02-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0022_auto_20190204_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='customer_id',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='customer id'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='subscription id'),
        ),
    ]
