# Generated by Django 2.0.6 on 2019-02-12 16:54

# Django
from django.db import migrations


def blank_to_null(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    Organization.objects.filter(customer_id='').update(customer_id=None)
    Organization.objects.filter(subscription_id='').update(subscription_id=None)

def null_to_blank(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    Organization.objects.filter(customer_id=None).update(customer_id='')
    Organization.objects.filter(subscription_id=None).update(subscription_id='')


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0023_auto_20190212_1654'),
    ]

    operations = [
            migrations.RunPython(blank_to_null, null_to_blank),
    ]
