# Generated by Django 2.1.7 on 2020-06-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0023_auto_20200526_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(help_text="The customer's corresponding ID on stripe", max_length=255, null=True, unique=True, verbose_name='customer id'),
        ),
    ]
