# Generated by Django 2.0.6 on 2019-02-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0024_auto_20190212_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='customer id'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='subscription id'),
        ),
    ]
