# Generated by Django 2.1.7 on 2021-02-22 20:38

# Django
from django.db import migrations

TYPES = {
    "Newsrooms": ["Print", "Online", "Radio", "Television", "Newsletter", "Book"],
    "NGO": ["Advocacy Organization"],
    "GLAM": ["Libraries and Archives", "Museums and Galleries"],
    "Academic": [
        "Journalism Education",
        "Student Newsroom",
        "Research",
        "Legal Clinics",
    ],
    "Professional": ["Law Firm", "Trade Association"],
}


def make_types(apps, schema_editor):
    """Create initial types and subtypes"""
    OrganizationType = apps.get_model("organizations", "OrganizationType")
    OrganizationSubtype = apps.get_model("organizations", "OrganizationSubtype")

    for type_name, subtypes in TYPES.items():
        type_ = OrganizationType.objects.create(name=type_name)
        for subtype in subtypes:
            OrganizationSubtype.objects.create(name=subtype, type=type_)


class Migration(migrations.Migration):

    dependencies = [("organizations", "0025_auto_20210222_1451")]

    operations = [migrations.RunPython(make_types, migrations.RunPython.noop)]
