# Generated by Django 3.2.11 on 2022-01-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0026_auto_20210222_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitlement',
            name='resources',
            field=models.JSONField(default=dict, help_text='Allows clients to track metadata for the resources this entitlement grants', verbose_name='resources'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subtypes',
            field=models.ManyToManyField(blank=True, help_text='The subtypes of this organization', related_name='organizations', to='organizations.OrganizationSubtype', verbose_name='subtypes'),
        ),
    ]
