# Generated by Django 2.1.7 on 2019-02-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0026_plan_private_organizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
