# Generated by Django 3.2.11 on 2022-04-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0027_auto_20220112_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='metadata',
            field=models.JSONField(default=dict, verbose_name='metadata'),
        ),
    ]
