# Generated by Django 2.1.7 on 2019-02-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0027_auto_20190214_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptemail',
            name='failed',
            field=models.BooleanField(default=False, verbose_name='failed'),
        ),
    ]
