# Generated by Django 3.2.11 on 2022-08-17 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0028_charge_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Organizations which are members of a trade association or other member group', related_name='groups', to='organizations.Organization', verbose_name='members'),
        ),
        migrations.AddField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The parent organization', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organizations.organization', verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='organization',
            name='wikidata_id',
            field=models.CharField(blank=True, help_text='The wikidata identifier', max_length=255, verbose_name='wikidata id'),
        ),
        migrations.CreateModel(
            name='OrganizationUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='url')),
                ('organization', models.ForeignKey(help_text='The organization to associate the URL with', on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='organizations.organization', verbose_name='organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationEmailDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, verbose_name='domain')),
                ('organization', models.ForeignKey(help_text='The organization to associate the email domain with', on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='organizations.organization', verbose_name='organization')),
            ],
        ),
    ]
