# Generated by Django 2.1.7 on 2019-03-07 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0023_auto_20190207_1452'),
        ('organizations', '0028_receiptemail_failed'),
    ]

    operations = [
    ]
