# Generated by Django 2.1.7 on 2019-03-06 17:06

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0028_receiptemail_failed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255, verbose_name='name'),
        ),
    ]
