# Generated by Django 2.1.7 on 2019-03-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0029_merge_20190307_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='customer id'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='subscription id'),
        ),
    ]
