# Generated by Django 3.2.11 on 2022-08-17 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0029_auto_20220817_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Organizations which are members of this organization (useful for trade associations or other member groups)', limit_choices_to={'individual': False}, related_name='groups', to='organizations.Organization', verbose_name='members'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The parent organization', limit_choices_to={'individual': False}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organizations.organization', verbose_name='parent'),
        ),
    ]
