# Generated by Django 2.1.7 on 2019-03-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0031_membership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.IntegerField(choices=[(0, 'Disabled'), (1, 'Administrator'), (2, 'Contributor'), (3, 'Reviewer'), (4, 'Freelancer')], default=1),
        ),
    ]
