# Generated by Django 2.1.7 on 2019-03-14 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0032_auto_20190313_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='admin',
        ),
    ]
