# Generated by Django 3.2.11 on 2024-03-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0033_alter_receiptemail_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationchangelog',
            name='credit_card',
            field=models.CharField(default='', help_text='The updated credit card number', max_length=255, verbose_name='credit card'),
        ),
        migrations.AlterField(
            model_name='organizationchangelog',
            name='reason',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Created'), (1, 'Updated'), (2, 'Failed'), (3, 'Credit Card')], help_text='Which category of change occurred', verbose_name='reason'),
        ),
    ]
