# Generated by Django 2.1.7 on 2019-03-14 02:20

from django.db import migrations
import django.utils.timezone
import squarelet.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0033_remove_membership_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='created_at',
            field=squarelet.core.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
    ]
