# Generated by Django 4.2 on 2024-04-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0034_auto_20240304_1245"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="verified_journalist",
            field=models.BooleanField(
                default=False,
                help_text="This organization is a verified journalistic organization",
                verbose_name="verified journalist",
            ),
        ),
    ]
