# Generated by Django 4.2 on 2024-05-22 16:25

# Django
from django.db import migrations


def make_types(apps, schema_editor):
    """Create some more types"""
    OrganizationType = apps.get_model("organizations", "OrganizationType")
    OrganizationSubtype = apps.get_model("organizations", "OrganizationSubtype")

    newsrooms = OrganizationType.objects.get(name="Newsroom")
    OrganizationSubtype.objects.create(name="Nonprofit", type=newsrooms)

    reach = OrganizationType.objects.create(name="Reach")
    for subtype in ["Local", "State", "Regional", "National", "Global"]:
        OrganizationSubtype.objects.create(name=subtype, type=reach)


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0035_organization_city_organization_country_and_more"),
    ]

    operations = [migrations.RunPython(make_types, migrations.RunPython.noop)]
