# Generated by Django 4.2 on 2024-05-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0035_alter_organization_verified_journalist"),
        ("organizations", "0036_auto_20240522_1225"),
    ]

    operations = []
