# Generated by Django 4.2 on 2024-06-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0037_alter_organizationsubtype_options_and_more"),
        ("organizations", "0037_merge_20240528_1225"),
    ]

    operations = []
