# Generated by Django 4.2 on 2025-03-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0039_alter_invitation_email_alter_organization_max_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="allow_auto_join",
            field=models.BooleanField(
                default=False,
                help_text="Allow users to join automatically if one of their verified emails matches the email domain for this organization.",
            ),
        ),
    ]
