# Generated by Django 4.2.18 on 2025-04-10 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0039_alter_invitation_email_alter_organization_max_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="merged",
            field=models.ForeignKey(
                blank=True,
                help_text="The agency this agency was merged in to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="organizations.organization",
                verbose_name="merged into",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="merged_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this organization was merged",
                null=True,
                verbose_name="merged at",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="merged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="merged by",
            ),
        ),
    ]
