# Generated by Django 4.2 on 2025-04-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0040_organization_allow_auto_join"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="created_at",
            field=models.DateTimeField(
                help_text="When the user joined the organization", null=True
            ),
        ),
    ]
