# Generated by Django 4.2 on 2025-05-07 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0040_organization_merged_organization_merged_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "ordering": ("slug",),
                "permissions": (("merge_organization", "Can merge organizations"),),
            },
        ),
    ]
