# Generated by Django 4.2 on 2025-04-04 15:58

from django.db import migrations
import django.utils.timezone
import squarelet.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0041_membership_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="created_at",
            field=squarelet.core.fields.AutoCreatedField(
                blank=True,
                default=django.utils.timezone.now,
                editable=False,
                help_text="When this organization was created",
                null=True,
                verbose_name="created_at",
            ),
        ),
    ]
