# Generated by Django 4.2 on 2025-05-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0041_alter_organization_options"),
        ("organizations", "0042_alter_membership_created_at"),
    ]

    operations = []
