# Generated by Django 4.2.18 on 2025-08-11 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0043_merge_20250528_1028"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="wix",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="organization",
            name="merged",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization this organization was merged in to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="organizations.organization",
                verbose_name="merged into",
            ),
        ),
    ]
