# Generated by Django 4.2.18 on 2025-08-14 19:35

# Django
from django.db import migrations

PLANS = [
    {
        "name": "Sunlight Research Center - Basic",
        "slug": "src-basic",
        "minimum_users": 5,
        "base_price": 170,
        "price_per_user": 10,
        "public": False,
        "annual": False,
        "for_individuals": False,
        "for_groups": True,
        "wix": True,
    },
    {
        "name": "Sunlight Research Center - Basic (Annual)",
        "slug": "src-basic-annual",
        "minimum_users": 5,
        "base_price": 2000,
        "price_per_user": 120,
        "public": False,
        "annual": True,
        "for_individuals": False,
        "for_groups": True,
        "wix": True,
    },
    {
        "name": "Sunlight Research Center - Premium",
        "slug": "src-premium",
        "minimum_users": 5,
        "base_price": 340,
        "price_per_user": 10,
        "public": False,
        "annual": False,
        "for_individuals": False,
        "for_groups": True,
        "wix": True,
    },
    {
        "name": "Sunlight Research Center - Premium (Annual)",
        "slug": "src-premium-annual",
        "minimum_users": 5,
        "base_price": 4000,
        "price_per_user": 120,
        "public": False,
        "annual": True,
        "for_individuals": False,
        "for_groups": True,
        "wix": True,
    },
    {
        "name": "Sunlight Research Center - Enterprise",
        "slug": "src-enterprise",
        "minimum_users": 5,
        "base_price": 675,
        "price_per_user": 10,
        "public": False,
        "annual": False,
        "for_individuals": False,
        "for_groups": True,
        "wix": True,
    },
    {
        "name": "Sunlight Research Center - Enterprise (Annual)",
        "slug": "src-enterprise-annual",
        "minimum_users": 5,
        "base_price": 8000,
        "price_per_user": 120,
        "public": False,
        "annual": True,
        "for_individuals": False,
        "for_groups": True,
        "wix": True,
    },
]


def add_plans(apps, schema_editor):
    Plan = apps.get_model("organizations", "Plan")
    Entitlement = apps.get_model("organizations", "Entitlement")
    orgs = Entitlement.objects.filter(name="Organization")
    for plan in PLANS:
        p = Plan.objects.create(**plan)
        p.entitlements.add(*orgs)


def remove_plans(apps, schema_editor):
    Plan = apps.get_model("organizations", "Plan")
    Plan.objects.filter(wix=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0044_plan_wix_alter_organization_merged"),
    ]

    operations = [migrations.RunPython(add_plans, remove_plans)]
