# Generated by Django 4.2.18 on 2025-08-29 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0044_plan_slack_webhook_url_alter_organization_merged"),
        ("organizations", "0045_auto_20250814_1535"),
    ]

    operations = []
