# Generated by Django 4.2.18 on 2025-11-10 19:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0046_plan_benefits"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="about",
            field=models.TextField(
                blank=True,
                help_text="A short description of this organization",
                verbose_name="about",
            ),
        ),
        # just a grammar fix in help text
        migrations.AlterField(
            model_name="organization",
            name="users",
            field=models.ManyToManyField(
                help_text="The users in this organization",
                related_name="organizations",
                through="organizations.Membership",
                to=settings.AUTH_USER_MODEL,
                verbose_name="users",
            ),
        ),
    ]
