# Generated by Django 4.2.18 on 2025-10-02 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0046_plan_benefits"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_id",
                    models.CharField(
                        help_text="The invoice ID from Stripe",
                        max_length=255,
                        unique=True,
                        verbose_name="invoice id",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        help_text="Total amount in cents", verbose_name="amount"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="When payment is due",
                        null=True,
                        verbose_name="due date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("paid", "Paid"),
                            ("uncollectible", "Uncollectible"),
                            ("void", "Void"),
                        ],
                        default="draft",
                        help_text="Current status of the invoice",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        help_text="When the invoice was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last modification time",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="The organization this invoice belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="organizations.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        help_text="The subscription this invoice is for, if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="organizations.subscription",
                        verbose_name="subscription",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
