# Generated by Django 4.2.18 on 2025-12-10 21:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import squarelet.core.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0046_plan_benefits"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="collective_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable this organization to participate in the collective feature as a parent or membership group. Only staff can enable this via admin.",
                verbose_name="collective enabled",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="share_resources",
            field=models.BooleanField(
                default=True,
                help_text="Share resources (subscriptions, credits) with all children and member organizations. Global toggle that applies to all relationships.",
                verbose_name="share resources",
            ),
        ),
        migrations.CreateModel(
            name="OrganizationInvitation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID serves as secret token for this invitation in URLs",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "relationship_type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Member"), (1, "Child")],
                        help_text="Type of relationship: member (networked) or child (hierarchical)",
                        verbose_name="relationship type",
                    ),
                ),
                (
                    "request",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is a request TO JOIN from to_organization. False if this is an invitation FROM from_organization.",
                        verbose_name="request",
                    ),
                ),
                (
                    "created_at",
                    squarelet.core.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this invitation was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When accepted (NULL if pending)",
                        null=True,
                        verbose_name="accepted at",
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When rejected (NULL if pending)",
                        null=True,
                        verbose_name="rejected at",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Optional message from the inviter",
                        verbose_name="message",
                    ),
                ),
                (
                    "from_organization",
                    models.ForeignKey(
                        help_text="The organization extending the invitation or receiving the request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_org_invitations",
                        to="organizations.organization",
                        verbose_name="from organization",
                    ),
                ),
                (
                    "to_organization",
                    models.ForeignKey(
                        help_text="The organization being invited",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_org_invitations",
                        to="organizations.organization",
                        verbose_name="to organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
