# Generated by Django 4.2.18 on 2025-08-29 18:13

# Django
from django.db import migrations


def rename_sunlight_plans(apps, schema_editor):
    Plan = apps.get_model("organizations", "Plan")
    for plan in Plan.objects.filter(slug__startswith="src-"):
        plan.slug = plan.slug.replace("src-", "sunlight-")
        plan.save()


def rename_src_plans(apps, schema_editor):
    Plan = apps.get_model("organizations", "Plan")
    for plan in Plan.objects.filter(slug__startswith="sunlight-"):
        plan.slug = plan.slug.replace("sunlight-", "src-")
        plan.save()


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0046_merge_20250829_1224"),
    ]

    operations = [migrations.RunPython(rename_sunlight_plans, rename_src_plans)]
