# Generated by Django 4.2.18 on 2025-10-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0047_add_invoice_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="last_overdue_email_sent",
            field=models.DateField(
                blank=True,
                help_text="Date when the last overdue warning email was sent",
                null=True,
                verbose_name="last overdue email sent",
            ),
        ),
    ]
