# Generated by Django 4.2.18 on 2025-11-12 21:01

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import squarelet.core.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0047_organization_about_alter_organization_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileChangeRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    squarelet.core.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this organization was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    squarelet.core.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this organization was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="The name of the organization",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        blank=True,
                        help_text="A unique slug for use in URLs",
                        verbose_name="slug",
                    ),
                ),
                ("url", models.URLField(blank=True)),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="city"),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AK", "Alaska"),
                            ("AL", "Alabama"),
                            ("AR", "Arkansas"),
                            ("AZ", "Arizona"),
                            ("CA", "California"),
                            ("CO", "Colorado"),
                            ("CT", "Connecticut"),
                            ("DC", "District of Columbia"),
                            ("DE", "Delaware"),
                            ("FL", "Florida"),
                            ("GA", "Georgia"),
                            ("HI", "Hawaii"),
                            ("IA", "Iowa"),
                            ("ID", "Idaho"),
                            ("IL", "Illinois"),
                            ("IN", "Indiana"),
                            ("KS", "Kansas"),
                            ("KY", "Kentucky"),
                            ("LA", "Louisiana"),
                            ("MA", "Massachusetts"),
                            ("MD", "Maryland"),
                            ("ME", "Maine"),
                            ("MI", "Michigan"),
                            ("MN", "Minnesota"),
                            ("MO", "Missouri"),
                            ("MS", "Mississippi"),
                            ("MT", "Montana"),
                            ("NC", "North Carolina"),
                            ("ND", "North Dakota"),
                            ("NE", "Nebraska"),
                            ("NH", "New Hampshire"),
                            ("NJ", "New Jersey"),
                            ("NM", "New Mexico"),
                            ("NV", "Nevada"),
                            ("NY", "New York"),
                            ("OH", "Ohio"),
                            ("OK", "Oklahoma"),
                            ("OR", "Oregon"),
                            ("PA", "Pennsylvania"),
                            ("RI", "Rhode Island"),
                            ("SC", "South Carolina"),
                            ("SD", "South Dakota"),
                            ("TN", "Tennessee"),
                            ("TX", "Texas"),
                            ("UT", "Utah"),
                            ("VA", "Virginia"),
                            ("VT", "Vermont"),
                            ("WA", "Washington"),
                            ("WI", "Wisconsin"),
                            ("WV", "West Virginia"),
                            ("WY", "Wyoming"),
                            ("AS", "American Samoa"),
                            ("GU", "Guam"),
                            ("MP", "Northern Mariana Islands"),
                            ("PR", "Puerto Rico"),
                            ("VI", "Virgin Islands"),
                            ("AB", "Alberta"),
                            ("BC", "British Columbia"),
                            ("MB", "Manitoba"),
                            ("NB", "New Brunswick"),
                            ("NL", "Newfoundland and Labrador"),
                            ("NT", "Northwest Territories"),
                            ("NS", "Nova Scotia"),
                            ("NU", "Nunavut"),
                            ("ON", "Ontario"),
                            ("PE", "Prince Edward Island"),
                            ("QC", "Quebec"),
                            ("SK", "Saskatchewan"),
                            ("YT", "Yukon"),
                        ],
                        max_length=2,
                        verbose_name="state",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        choices=[("US", "United States of America"), ("CA", "Canada")],
                        max_length=2,
                        verbose_name="country",
                    ),
                ),
                (
                    "previous",
                    models.JSONField(
                        blank=True, editable=False, verbose_name="previous"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="The organization we want to update",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_change_requests",
                        to="organizations.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user making the request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_change_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
        ),
    ]
