# Generated by Django 4.2.18 on 2025-11-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0048_profilechangerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilechangerequest",
            name="explanation",
            field=models.TextField(
                blank=True,
                help_text="Reason for this proposed change",
                verbose_name="explanation",
            ),
        ),
    ]
