# Generated by Django 4.2.18 on 2025-12-12 13:52

from django.db import migrations, models


def add_plan_short_descriptions(apps, schema_editor):
    """Add short descriptions and update names for Sunlight Research plans"""
    Plan = apps.get_model("organizations", "Plan")

    # Update Basic plans
    Plan.objects.filter(
        name="Sunlight Research Center - Basic"
    ).update(
        name="Sunlight Research Desk Membership - Basic",
        short_description="Recommended for newsrooms with 5 or fewer staff and short-term projects"
    )

    Plan.objects.filter(
        name="Sunlight Research Center - Basic (Annual)"
    ).update(
        name="Sunlight Research Desk Membership - Basic (Annual)",
        short_description="Recommended for newsrooms with 5 or fewer staff and short-term projects"
    )

    # Update Premium plans
    Plan.objects.filter(
        name="Sunlight Research Center - Premium"
    ).update(
        name="Sunlight Research Desk Membership - Premium",
        short_description="Recommended for newsrooms with 6-20 staff and multiple projects"
    )

    Plan.objects.filter(
        name="Sunlight Resarch Center - Premium (Annual)"
    ).update(
        name="Sunlight Research Desk Membership - Premium (Annual)",
        short_description="Recommended for newsrooms with 6-20 staff and multiple projects"
    )

    # Update Enterprise plans
    Plan.objects.filter(
        name="Sunlight Research Center - Enterprise"
    ).update(
        name="Sunlight Research Desk Membership - Enterprise",
        short_description="Recommended for newsrooms with 20+ staff and/or complex requests"
    )

    Plan.objects.filter(
        name="Sunlight Resarch Center - Enterprise (Annual)"
    ).update(
        name="Sunlight Research Desk Membership - Enterprise (Annual)",
        short_description="Recommended for newsrooms with 20+ staff and/or complex requests"
    )


def reverse_plan_short_descriptions(apps, schema_editor):
    """Reverse the short descriptions and name changes"""
    Plan = apps.get_model("organizations", "Plan")

    # Reverse Basic plans
    Plan.objects.filter(
        name="Sunlight Research Desk Membership - Basic"
    ).update(
        name="Sunlight Research Center - Basic",
        short_description=""
    )

    Plan.objects.filter(
        name="Sunlight Research Desk Membership - Basic (Annual)"
    ).update(
        name="Sunlight Research Center - Basic (Annual)",
        short_description=""
    )

    # Reverse Premium plans
    Plan.objects.filter(
        name="Sunlight Research Desk Membership - Premium"
    ).update(
        name="Sunlight Research Center - Premium",
        short_description=""
    )

    Plan.objects.filter(
        name="Sunlight Research Desk Membership - Premium (Annual)"
    ).update(
        name="Sunlight Resarch Center - Premium (Annual)",
        short_description=""
    )

    # Reverse Enterprise plans
    Plan.objects.filter(
        name="Sunlight Research Desk Membership - Enterprise"
    ).update(
        name="Sunlight Research Center - Enterprise",
        short_description=""
    )

    Plan.objects.filter(
        name="Sunlight Research Desk Membership - Enterprise (Annual)"
    ).update(
        name="Sunlight Resarch Center - Enterprise (Annual)",
        short_description=""
    )


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0048_add_last_overdue_email_sent_to_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="short_description",
            field=models.TextField(
                blank=True,
                help_text="A short description of the plan, used in lists",
                verbose_name="description",
            ),
        ),
        migrations.RunPython(
            add_plan_short_descriptions,
            reverse_plan_short_descriptions,
        ),
    ]
