# Generated by Django 4.2.18 on 2026-01-08 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0047_organization_collective_enabled_and_more"),
        ("organizations", "0048_add_last_overdue_email_sent_to_invoice"),
    ]

    operations = []
