# Generated by Django 4.2.18 on 2025-11-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0049_profilechangerequest_explanation"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilechangerequest",
            name="ticket_id",
            field=models.IntegerField(
                blank=True,
                help_text="Ticket ID on Zendesk",
                null=True,
                verbose_name="ticket_id",
            ),
        ),
    ]
