# Generated by Django 4.2.18 on 2025-08-14 19:35

# Django
from django.db import migrations

# Standard Library
import stripe
from django.conf import settings

stripe.api_version = "2018-09-24"
stripe.api_key = settings.STRIPE_SECRET_KEY


def update_and_add_plans(apps, schema_editor):
    """Update existing Sunlight plans and create nonprofit variants"""
    Plan = apps.get_model("organizations", "Plan")
    Entitlement = apps.get_model("organizations", "Entitlement")
    orgs = Entitlement.objects.filter(name="Organization")

    # Skip Stripe API calls in test environment (test key starts with sk_muckrock)
    is_test_env = settings.STRIPE_SECRET_KEY.startswith("sk_muckrock")

    # Define benefits for each plan tier
    essential_benefits = [
        "50 research desk hours per year",
        "Two small projects or one medium project",
        "One investigative training session of your choice, delivered to your team on your schedule",
        "Monthly workshops and investigative office hours",
        "Real-time research support from Sunlight experts",
        "Premium MuckRock account, including 50 free public records requests each month and credits for DocumentCloud AI tools",
    ]

    enhanced_benefits = [
        "100 research desk hours per year",
        "Four small projects or two medium project",
        "One investigative training session of your choice, delivered to your team on your schedule",
        "Monthly workshops and investigative office hours",
        "Real-time research support from Sunlight experts",
        "Premium MuckRock account, including 50 free public records requests each month and credits for DocumentCloud AI tools",
    ]

    enterprise_benefits = [
        "Tailored support and training to meet your newsroom needs",
    ]

    # Update existing plans (rename slugs, names, pricing, and benefits)
    plan_updates = [
        {
            "old_slug": "sunlight-basic",
            "new_slug": "sunlight-essential",
            "name": "Sunlight Research Center - Essential",
            "base_price": 350,
            "benefits": essential_benefits,
        },
        {
            "old_slug": "sunlight-basic-annual",
            "new_slug": "sunlight-essential-annual",
            "name": "Sunlight Research Center - Essential (Annual)",
            "base_price": 4000,
            "benefits": essential_benefits,
        },
        {
            "old_slug": "sunlight-premium",
            "new_slug": "sunlight-enhanced",
            "name": "Sunlight Research Center - Enhanced",
            "base_price": 680,
            "benefits": enhanced_benefits,
        },
        {
            "old_slug": "sunlight-premium-annual",
            "new_slug": "sunlight-enhanced-annual",
            "name": "Sunlight Research Center - Enhanced (Annual)",
            "base_price": 8000,
            "benefits": enhanced_benefits,
        },
        {
            "old_slug": "sunlight-enterprise",
            "new_slug": "sunlight-enterprise",
            "name": "Sunlight Research Center - Enterprise",
            "base_price": 1200,
            "benefits": enterprise_benefits,
        },
        {
            "old_slug": "sunlight-enterprise-annual",
            "new_slug": "sunlight-enterprise-annual",
            "name": "Sunlight Research Center - Enterprise (Annual)",
            "base_price": 12000,
            "benefits": enterprise_benefits,
        },
    ]

    for update in plan_updates:
        Plan.objects.filter(slug=update["old_slug"]).update(
            slug=update["new_slug"],
            name=update["name"],
            base_price=update["base_price"],
            benefits=update["benefits"],
        )

    # Create nonprofit variants (50% discount)
    nonprofit_plans = [
        {
            "name": "Sunlight Research Center - Essential (Non-Profit)",
            "slug": "sunlight-nonprofit-essential",
            "minimum_users": 5,
            "base_price": 175,  # 50% of 350
            "price_per_user": 10,
            "public": False,
            "annual": False,
            "for_individuals": False,
            "for_groups": True,
            "wix": True,
            "benefits": essential_benefits,
        },
        {
            "name": "Sunlight Research Center - Essential (Annual, Non-Profit)",
            "slug": "sunlight-nonprofit-essential-annual",
            "minimum_users": 5,
            "base_price": 2000,  # 50% of 4000
            "price_per_user": 120,
            "public": False,
            "annual": True,
            "for_individuals": False,
            "for_groups": True,
            "wix": True,
            "benefits": essential_benefits,
        },
        {
            "name": "Sunlight Research Center - Enhanced (Non-Profit)",
            "slug": "sunlight-nonprofit-enhanced",
            "minimum_users": 5,
            "base_price": 340,  # 50% of 680
            "price_per_user": 10,
            "public": False,
            "annual": False,
            "for_individuals": False,
            "for_groups": True,
            "wix": True,
            "benefits": enhanced_benefits,
        },
        {
            "name": "Sunlight Research Center - Enhanced (Annual, Non-Profit)",
            "slug": "sunlight-nonprofit-enhanced-annual",
            "minimum_users": 5,
            "base_price": 4000,  # 50% of 8000
            "price_per_user": 120,
            "public": False,
            "annual": True,
            "for_individuals": False,
            "for_groups": True,
            "wix": True,
            "benefits": enhanced_benefits,
        },
    ]

    for plan_data in nonprofit_plans:
        plan = Plan.objects.create(**plan_data)
        plan.entitlements.add(*orgs)

        # Create the corresponding Stripe plan manually
        # Historical models don't have custom methods, so we recreate the logic here
        # See Plan.make_stripe_plan() in squarelet/organizations/models/payment.py:569-601
        # Skip Stripe API calls in test environments
        if not is_test_env and (not plan.base_price == 0 or not plan.price_per_user == 0):
            stripe_plan_id = f"squarelet_plan_{plan.slug}"
            try:
                # Tiered pricing for group plans
                kwargs = {
                    "billing_scheme": "tiered",
                    "tiers": [
                        {
                            "flat_amount": 100 * plan.base_price,
                            "up_to": plan.minimum_users,
                        },
                        {"unit_amount": 100 * plan.price_per_user, "up_to": "inf"},
                    ],
                    "tiers_mode": "graduated",
                }
                stripe.Plan.create(
                    id=stripe_plan_id,
                    currency="usd",
                    interval="year" if plan.annual else "month",
                    product={"name": plan.name, "unit_label": "Seats"},
                    **kwargs,
                )
            except stripe.error.InvalidRequestError:
                # If the plan already exists, just skip
                pass


def reverse_changes(apps, schema_editor):
    """Revert plan updates and remove nonprofit variants"""
    Plan = apps.get_model("organizations", "Plan")

    # Skip Stripe API calls in test environment (test key starts with sk_muckrock)
    is_test_env = settings.STRIPE_SECRET_KEY.startswith("sk_muckrock")

    # Revert plan slugs, names, pricing, and benefits
    plan_reverts = [
        {
            "current_slug": "sunlight-essential",
            "old_slug": "sunlight-basic",
            "name": "Sunlight Research Center - Basic",
            "base_price": 170,
            "benefits": [],
        },
        {
            "current_slug": "sunlight-essential-annual",
            "old_slug": "sunlight-basic-annual",
            "name": "Sunlight Research Center - Basic (Annual)",
            "base_price": 2000,
            "benefits": [],
        },
        {
            "current_slug": "sunlight-enhanced",
            "old_slug": "sunlight-premium",
            "name": "Sunlight Research Center - Premium",
            "base_price": 340,
            "benefits": [],
        },
        {
            "current_slug": "sunlight-enhanced-annual",
            "old_slug": "sunlight-premium-annual",
            "name": "Sunlight Research Center - Premium (Annual)",
            "base_price": 4000,
            "benefits": [],
        },
        {
            "current_slug": "sunlight-enterprise",
            "old_slug": "sunlight-enterprise",
            "name": "Sunlight Research Center - Enterprise",
            "base_price": 675,
            "benefits": [],
        },
        {
            "current_slug": "sunlight-enterprise-annual",
            "old_slug": "sunlight-enterprise-annual",
            "name": "Sunlight Research Center - Enterprise (Annual)",
            "base_price": 8000,
            "benefits": [],
        },
    ]

    for revert in plan_reverts:
        Plan.objects.filter(slug=revert["current_slug"]).update(
            slug=revert["old_slug"],
            name=revert["name"],
            base_price=revert["base_price"],
            benefits=revert["benefits"],
        )

    # Delete Stripe plans for nonprofit variants before deleting DB records
    # See Plan.delete_stripe_plan() in squarelet/organizations/models/payment.py:603-613
    # Skip Stripe API calls in test environments
    nonprofit_plans = Plan.objects.filter(slug__startswith="sunlight-nonprofit-")
    if not is_test_env:
        for plan in nonprofit_plans:
            stripe_plan_id = f"squarelet_plan_{plan.slug}"
            try:
                stripe_plan = stripe.Plan.retrieve(id=stripe_plan_id)
                # Also remove the associated product
                product = stripe.Product.retrieve(id=stripe_plan.product)
                stripe_plan.delete()
                product.delete()
            except stripe.error.InvalidRequestError:
                # If the plan or product do not exist, just skip
                pass

    # Delete nonprofit variants from database
    nonprofit_plans.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0049_plan_short_description"),
    ]

    operations = [
        migrations.RunPython(update_and_add_plans, reverse_changes),
    ]
