# Generated by Django 4.2.18 on 2026-01-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0049_merge_20260108_1319"),
        ("organizations", "0049_plan_short_description"),
    ]

    operations = []
