# Generated by Django 4.2.18 on 2025-08-14 19:35

# Django
from django.db import migrations, models

# Standard Library
import stripe
from django.conf import settings

stripe.api_version = "2018-09-24"
stripe.api_key = settings.STRIPE_SECRET_KEY


def update_and_add_plans(apps, schema_editor):
    """Create new Sunlight plans and mark old ones as private, and create nonprofit variants"""
    Plan = apps.get_model("organizations", "Plan")
    Entitlement = apps.get_model("organizations", "Entitlement")
    orgs = Entitlement.objects.filter(name="Organization")

    # Skip Stripe API calls in test environment (test key starts with sk_muckrock)
    is_test_env = settings.STRIPE_SECRET_KEY.startswith("sk_muckrock")

    # Define benefits for each plan tier
    essential_benefits = [
        "50 hours of research team time for your projects",
        "One investigative training session of your choice, delivered to your team on your schedule",
        "Monthly workshops and investigative office hours",
        "Real-time research support from Sunlight experts",
        "Premium MuckRock account, including 50 free public records requests each month and credits for DocumentCloud AI tools",
        "Investigative consult call with Sunlight researchers for real-time collaboration",
    ]

    enhanced_benefits = [
        "100 hours of research team time for your projects",
        "One investigative training session of your choice, delivered to your team on your schedule",
        "Monthly workshops and investigative office hours",
        "Real-time research support from Sunlight experts",
        "Premium MuckRock account, including 50 free public records requests each month and credits for DocumentCloud AI tools",
        "Two investigative consult calls with Sunlight researchers for real-time collaboration",
    ]

    enterprise_benefits = [
        "Our Sunlight research experts will work with your organization to develop a plan that best supports your investigative and accountability reporting goals.",
    ]

    # Define short descriptions for each plan tier
    essential_short_description = "Ideal for small to medium local newsrooms with big goals."
    enhanced_short_description = "Ideal for medium to large teams tackling ambitious projects."
    enterprise_short_description = "Ideal for large newsrooms, collaboratives, complex, long-term project assistance, tailored investigative training needs."

    # Mark old plans as private (no longer purchasable, but remain in DB for existing subscriptions)
    old_plan_slugs = [
        "sunlight-basic",
        "sunlight-basic-annual",
        "sunlight-premium",
        "sunlight-premium-annual",
    ]
    Plan.objects.filter(slug__in=old_plan_slugs).update(public=False)

    # Create new plans with updated pricing and benefits
    new_plans = [
        {
            "name": "Sunlight Research Center - Essential",
            "slug": "sunlight-essential",
            "minimum_users": 5,
            "base_price": 680,
            "price_per_user": 20,
            "public": True,
            "annual": False,
            "for_individuals": False,
            "for_groups": True,
            "wix": True,
            "short_description": essential_short_description,
            "benefits": essential_benefits,
        },
        {
            "name": "Sunlight Research Center - Essential (Annual)",
            "slug": "sunlight-essential-annual",
            "minimum_users": 5,
            "base_price": 8000,
            "price_per_user": 240,
            "public": True,
            "annual": True,
            "for_individuals": False,
            "for_groups": True,
            "wix": True,
            "short_description": essential_short_description,
            "benefits": essential_benefits,
        },
        {
            "name": "Sunlight Research Center - Enhanced",
            "slug": "sunlight-enhanced",
            "minimum_users": 5,
            "base_price": 1380,
            "price_per_user": 20,
            "public": True,
            "annual": False,
            "for_individuals": False,
            "for_groups": True,
            "wix": True,
            "short_description": enhanced_short_description,
            "benefits": enhanced_benefits,
        },
        {
            "name": "Sunlight Research Center - Enhanced (Annual)",
            "slug": "sunlight-enhanced-annual",
            "minimum_users": 5,
            "base_price": 16000,
            "price_per_user": 240,
            "public": True,
            "annual": True,
            "for_individuals": False,
            "for_groups": True,
            "wix": True,
            "short_description": enhanced_short_description,
            "benefits": enhanced_benefits,
        },
    ]

    # Update Enterprise plans (only update benefits and description, keep existing pricing)
    enterprise_updates = [
        {
            "slug": "sunlight-enterprise",
            "name": "Sunlight Research Center - Enterprise",
            "base_price": 2750,
            "short_description": enterprise_short_description,
            "benefits": enterprise_benefits,
        },
        {
            "slug": "sunlight-enterprise-annual",
            "name": "Sunlight Research Center - Enterprise (Annual)",
            "base_price": 32000,
            "short_description": enterprise_short_description,
            "benefits": enterprise_benefits,
        },
    ]

    for update in enterprise_updates:
        Plan.objects.filter(slug=update["slug"]).update(
            name=update["name"],
            base_price=update["base_price"],
            short_description=update["short_description"],
            benefits=update["benefits"],
        )

    # Create new Essential and Enhanced plans
    for plan_data in new_plans:
        slug = plan_data.pop("slug")
        plan, created = Plan.objects.update_or_create(slug=slug, defaults=plan_data)
        plan.entitlements.add(*orgs)

        # Create the corresponding Stripe plan
        # Skip Stripe API calls in test environments
        if not is_test_env and (not plan.base_price == 0 or not plan.price_per_user == 0):
            stripe_plan_id = f"squarelet_plan_{plan.slug}"
            try:
                # Tiered pricing for group plans
                kwargs = {
                    "billing_scheme": "tiered",
                    "tiers": [
                        {
                            "flat_amount": 100 * plan.base_price,
                            "up_to": plan.minimum_users,
                        },
                        {"unit_amount": 100 * plan.price_per_user, "up_to": "inf"},
                    ],
                    "tiers_mode": "graduated",
                }
                stripe.Plan.create(
                    id=stripe_plan_id,
                    currency="usd",
                    interval="year" if plan.annual else "month",
                    product={"name": plan.name, "unit_label": "Seats"},
                    **kwargs,
                )
            except stripe.error.InvalidRequestError:
                # If the plan already exists, just skip
                pass

    # Create nonprofit variants (50% discount)
    nonprofit_plans = [
        {
            "name": "Sunlight Research Center - Essential (Non-Profit)",
            "slug": "sunlight-nonprofit-essential",
            "minimum_users": 5,
            "base_price": 350,
            "price_per_user": 10,
            "public": False,
            "annual": False,
            "for_individuals": False,
            "for_groups": True,
            "wix": True,
            "short_description": essential_short_description,
            "benefits": essential_benefits,
        },
        {
            "name": "Sunlight Research Center - Essential (Annual, Non-Profit)",
            "slug": "sunlight-nonprofit-essential-annual",
            "minimum_users": 5,
            "base_price": 4000,
            "price_per_user": 120,
            "public": False,
            "annual": True,
            "for_individuals": False,
            "for_groups": True,
            "wix": True,
            "short_description": essential_short_description,
            "benefits": essential_benefits,
        },
        {
            "name": "Sunlight Research Center - Enhanced (Non-Profit)",
            "slug": "sunlight-nonprofit-enhanced",
            "minimum_users": 5,
            "base_price": 680,
            "price_per_user": 10,
            "public": False,
            "annual": False,
            "for_individuals": False,
            "for_groups": True,
            "wix": True,
            "short_description": enhanced_short_description,
            "benefits": enhanced_benefits,
        },
        {
            "name": "Sunlight Research Center - Enhanced (Annual, Non-Profit)",
            "slug": "sunlight-nonprofit-enhanced-annual",
            "minimum_users": 5,
            "base_price": 8000,
            "price_per_user": 120,
            "public": False,
            "annual": True,
            "for_individuals": False,
            "for_groups": True,
            "wix": True,
            "short_description": enhanced_short_description,
            "benefits": enhanced_benefits,
        },
    ]

    for plan_data in nonprofit_plans:
        slug = plan_data.pop("slug")
        plan, created = Plan.objects.update_or_create(slug=slug, defaults=plan_data)
        plan.entitlements.add(*orgs)

        # Create the corresponding Stripe plan manually
        # Historical models don't have custom methods, so we recreate the logic here
        # See Plan.make_stripe_plan() in squarelet/organizations/models/payment.py:569-601
        # Skip Stripe API calls in test environments
        if not is_test_env and (not plan.base_price == 0 or not plan.price_per_user == 0):
            stripe_plan_id = f"squarelet_plan_{plan.slug}"
            try:
                # Tiered pricing for group plans
                kwargs = {
                    "billing_scheme": "tiered",
                    "tiers": [
                        {
                            "flat_amount": 100 * plan.base_price,
                            "up_to": plan.minimum_users,
                        },
                        {"unit_amount": 100 * plan.price_per_user, "up_to": "inf"},
                    ],
                    "tiers_mode": "graduated",
                }
                stripe.Plan.create(
                    id=stripe_plan_id,
                    currency="usd",
                    interval="year" if plan.annual else "month",
                    product={"name": plan.name, "unit_label": "Seats"},
                    **kwargs,
                )
            except stripe.error.InvalidRequestError:
                # If the plan already exists, just skip
                pass


def reverse_changes(apps, schema_editor):
    """Revert plan changes and remove nonprofit variants"""
    Plan = apps.get_model("organizations", "Plan")
    OrganizationChangeLog = apps.get_model("organizations", "OrganizationChangeLog")

    # Skip Stripe API calls in test environment (test key starts with sk_muckrock)
    is_test_env = settings.STRIPE_SECRET_KEY.startswith("sk_muckrock")

    # Make old plans public again
    old_plan_slugs = [
        "sunlight-basic",
        "sunlight-basic-annual",
        "sunlight-premium",
        "sunlight-premium-annual",
    ]
    Plan.objects.filter(slug__in=old_plan_slugs).update(public=True)

    # Revert Enterprise plan updates
    enterprise_reverts = [
        {
            "slug": "sunlight-enterprise",
            "name": "Sunlight Research Center - Enterprise",
            "base_price": 675,
            "short_description": "",
            "benefits": [],
        },
        {
            "slug": "sunlight-enterprise-annual",
            "name": "Sunlight Research Center - Enterprise (Annual)",
            "base_price": 8000,
            "short_description": "",
            "benefits": [],
        },
    ]

    for revert in enterprise_reverts:
        Plan.objects.filter(slug=revert["slug"]).update(
            name=revert["name"],
            base_price=revert["base_price"],
            short_description=revert["short_description"],
            benefits=revert["benefits"],
        )

    # Delete new Essential and Enhanced plans from Stripe
    new_plan_slugs = [
        "sunlight-essential",
        "sunlight-essential-annual",
        "sunlight-enhanced",
        "sunlight-enhanced-annual",
    ]

    if not is_test_env:
        for slug in new_plan_slugs:
            stripe_plan_id = f"squarelet_plan_{slug}"
            try:
                stripe_plan = stripe.Plan.retrieve(id=stripe_plan_id)
                product = stripe.Product.retrieve(id=stripe_plan.product)
                stripe_plan.delete()
                product.delete()
            except stripe.error.InvalidRequestError:
                # If the plan or product do not exist, just skip
                pass

    # Delete OrganizationChangeLog entries referencing the new plans before deleting plans
    new_plans = Plan.objects.filter(slug__in=new_plan_slugs)
    OrganizationChangeLog.objects.filter(
        models.Q(from_plan__in=new_plans) | models.Q(to_plan__in=new_plans)
    ).delete()

    # Delete new Essential and Enhanced plans from database
    new_plans.delete()

    # Delete Stripe plans for nonprofit variants before deleting DB records
    # See Plan.delete_stripe_plan() in squarelet/organizations/models/payment.py:603-613
    # Skip Stripe API calls in test environments
    nonprofit_plans = Plan.objects.filter(slug__startswith="sunlight-nonprofit-")
    if not is_test_env:
        for plan in nonprofit_plans:
            stripe_plan_id = f"squarelet_plan_{plan.slug}"
            try:
                stripe_plan = stripe.Plan.retrieve(id=stripe_plan_id)
                # Also remove the associated product
                product = stripe.Product.retrieve(id=stripe_plan.product)
                stripe_plan.delete()
                product.delete()
            except stripe.error.InvalidRequestError:
                # If the plan or product do not exist, just skip
                pass

    # Delete OrganizationChangeLog entries referencing nonprofit plans before deleting plans
    OrganizationChangeLog.objects.filter(
        models.Q(from_plan__in=nonprofit_plans) | models.Q(to_plan__in=nonprofit_plans)
    ).delete()

    # Delete nonprofit variants from database
    nonprofit_plans.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0050_merge_20260122_1344"),
    ]

    operations = [
        migrations.RunPython(update_and_add_plans, reverse_changes),
    ]
