# Generated by Django 4.2.18 on 2025-12-03 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0048_add_last_overdue_email_sent_to_invoice"),
        ("organizations", "0050_profilechangerequest_ticket_id"),
    ]

    operations = []
