# Generated by Django 4.2.18 on 2025-12-08 18:56

from django.db import migrations
import django.utils.timezone
import squarelet.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0050_profilechangerequest_ticket_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilechangerequest",
            name="created_at",
            field=squarelet.core.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="When this request was created",
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="profilechangerequest",
            name="updated_at",
            field=squarelet.core.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="When this request was last updated",
                verbose_name="updated at",
            ),
        ),
    ]
