# Generated by Django 4.2.18 on 2026-01-15 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0049_plan_short_description"),
        ("organizations", "0052_alter_profilechangerequest_created_at_and_more"),
    ]

    operations = []
