# Generated by Django 4.2.18 on 2026-01-28 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0051_update_sunlight_plans_and_add_nonprofit_variants"),
        ("organizations", "0053_merge_20260115_1325"),
    ]

    operations = []
