# Generated by Django 4.2.18 on 2026-02-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0054_merge_20260128_1535"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "ordering": ("slug",),
                "permissions": (
                    ("merge_organization", "Can merge organizations"),
                    ("can_manage_members", "Can manage organization members"),
                    ("can_view_members", "Can view organization members"),
                    (
                        "can_review_profile_changes",
                        "Can review profile change requests",
                    ),
                    (
                        "can_view_subscription",
                        "Can view organization subscription",
                    ),
                    (
                        "can_edit_subscription",
                        "Can edit organization subscription",
                    ),
                    (
                        "can_view_charge",
                        "Can view charge receipts",
                    ),
                ),
            },
        ),
    ]
