# Generated by Django 4.2.18 on 2026-02-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0054_merge_20260128_1535"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "ordering": ("slug",),
                "permissions": (
                    ("merge_organization", "Can merge organizations"),
                    ("can_manage_members", "Can manage organization members"),
                ),
            },
        ),
    ]
