# Generated by Django 4.2.18 on 2026-02-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0055_alter_organization_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="withdrawn_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this invitation was withdrawn.  NULL signifies it has not been withdrawn yet",
                null=True,
                verbose_name="withdrawn at",
            ),
        ),
        migrations.AddField(
            model_name="organizationinvitation",
            name="withdrawn_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When withdrawn (NULL if pending)",
                null=True,
                verbose_name="withdrawn at",
            ),
        ),
    ]
