# Generated by Django 4.2.18 on 2026-02-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0056_invitation_withdrawn_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilechangerequest",
            name="internal_note",
            field=models.TextField(
                blank=True,
                help_text="Internal staff note about a change request visible only to organization staff",
                verbose_name="internal note",
            ),
        ),
    ]
