# Generated by Django 4.2.18 on 2026-01-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0057_profilechangerequest_internal_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Member"), (1, "Admin")],
                default=0,
                help_text="The role this user will have when accepting the invitation",
                verbose_name="role",
            ),
        ),
    ]
