# Generated by Django 5.2.11 on 2026-03-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0058_invitation_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="hidden",
            field=models.BooleanField(
                default=True,
                help_text="Individual accounts are hidden until the user has verified their email, made a payment, or been verified by association. Hidden accounts do not appear in search results.",
                verbose_name="hidden",
            ),
        ),
    ]
