# Generated by Django 5.2.11 on 2026-03-24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0060_populate_hidden"),
        ("organizations", "0059_alter_organization_options"),
    ]

    operations = []
