# Generated by Django 5.2.12 on 2026-05-19 00:18

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0061_merge_20260324"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=True,
                help_text="A unique slug to identify the plan",
                populate_from="name",
                unique=True,
                verbose_name="slug",
            ),
        ),
        migrations.CreateModel(
            name="EntitlementGrant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
                (
                    "require_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Match organizations whose verified_journalist=True",
                        verbose_name="require verified",
                    ),
                ),
                (
                    "require_active_subscription",
                    models.BooleanField(
                        default=False,
                        help_text="Match organizations with at least one active subscription",
                        verbose_name="require active subscription",
                    ),
                ),
                (
                    "for_individuals",
                    models.BooleanField(
                        default=True,
                        help_text="Apply this grant to individual organizations",
                        verbose_name="for individuals",
                    ),
                ),
                (
                    "for_groups",
                    models.BooleanField(
                        default=True,
                        help_text="Apply this grant to non-individual organizations",
                        verbose_name="for groups",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive grants do not apply to any organization",
                        verbose_name="active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entitlements",
                    models.ManyToManyField(
                        help_text="Entitlements this grant extends",
                        related_name="grants",
                        to="organizations.entitlement",
                        verbose_name="entitlements",
                    ),
                ),
                (
                    "organizations",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Organizations explicitly granted these entitlements",
                        related_name="entitlement_grants",
                        to="organizations.organization",
                        verbose_name="organizations",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "name"),
            },
        ),
    ]
