# Generated by Django 5.2.12 on 2026-05-19 17:51

from datetime import date

from dateutil.relativedelta import relativedelta
from django.db import migrations, models


def backfill_update_on(apps, schema_editor):
    """Populate update_on for any pre-existing grants so admins see consistent
    values. NULL <= today is false in SQL, so the celery task wouldn't sweep
    these without backfill, but admins inspecting the table would see blanks."""
    EntitlementGrant = apps.get_model("organizations", "EntitlementGrant")
    EntitlementGrant.objects.filter(update_on__isnull=True).update(
        update_on=date.today() + relativedelta(months=1)
    )


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0062_alter_plan_slug_entitlementgrant"),
    ]

    operations = [
        migrations.AddField(
            model_name="entitlementgrant",
            name="update_on",
            field=models.DateField(
                blank=True,
                help_text="Date when this grant's resources next refresh",
                null=True,
                verbose_name="date update",
            ),
        ),
        migrations.RunPython(backfill_update_on, migrations.RunPython.noop),
    ]
