# Generated by Django 5.2.12 on 2026-05-26 18:43

import squarelet.organizations.models.payment
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0063_entitlementgrant_update_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entitlementgrant",
            name="update_on",
            field=models.DateField(
                blank=True,
                default=squarelet.organizations.models.payment.default_grant_update_on,
                help_text="Date when this grant's resources next refresh",
                null=True,
                verbose_name="date update",
            ),
        ),
    ]
