# Generated by Django 5.2.11 on 2026-06-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0064_alter_entitlementgrant_update_on"),
        ("organizations", "0064_remove_organization_next_plan"),
    ]

    operations = []
