# Generated by Django 5.2.12 on 2026-07-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0068_subscription_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="auto_renew",
            field=models.BooleanField(
                default=True,
                help_text="Automatically renew subscriptions to this plan at the end of each billing period. Disable for plans, such as high-value annual plans, that should not automatically renew.",
                verbose_name="auto renew",
            ),
        ),
    ]
