# Generated by Django 5.2.12 on 2026-07-14 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0068_subscription_quantity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "ordering": ("slug",),
                "permissions": (
                    ("merge_organization", "Can merge organizations"),
                    ("can_manage_members", "Can manage organization members"),
                    ("can_view_members", "Can view organization members"),
                    (
                        "can_review_profile_changes",
                        "Can review profile change requests",
                    ),
                    ("can_view_subscription", "Can view organization subscription"),
                    ("can_edit_subscription", "Can edit organization subscription"),
                    ("can_view_charge", "Can view charge receipts"),
                    ("can_manage_domains", "Can manage organization email domains"),
                    ("can_manage_member_orgs", "Can manage member organizations"),
                ),
            },
        ),
    ]
