# Generated by Django 5.2.11 on 2026-07-14 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0069_plan_auto_renew"),
        ("organizations", "0071_subscription_cancel_at"),
    ]

    operations = []
