# Generated by Django 5.2.11 on 2026-07-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0062_invoice_hosted_invoice_url"),
        ("organizations", "0072_merge_20260714_1639"),
    ]

    operations = []
