# Generated by Django 5.2.11 on 2026-07-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0073_merge_20260716_0928"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="card_brand",
            new_name="payment_brand",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="card_exp_month",
            new_name="payment_exp_month",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="card_exp_year",
            new_name="payment_exp_year",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="card_last4",
            new_name="payment_last4",
        ),
    ]
