# Generated by Django 5.2.12 on 2026-07-24 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0070_alter_organization_options"),
        ("organizations", "0073_merge_20260716_0928"),
    ]

    operations = []
