# Generated by Django 5.2.11 on 2026-08-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0076_plan_tiers_and_packs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planprice",
            name="stripe_price_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The Price ID on stripe.  Blank for comped prices: those never create a Stripe subscription, so they have no Stripe counterpart to point at.  Uniqueness is enforced only on non-blank values.",
                max_length=255,
                verbose_name="stripe price id",
            ),
        ),
        migrations.AddConstraint(
            model_name="planprice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("stripe_price_id", ""), _negated=True),
                fields=("stripe_price_id",),
                name="unique_stripe_price_id_when_set",
            ),
        ),
    ]
