# Generated by Django 5.2.11 on 2026-07-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0076_remove_customer_payment_cache_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="method_type",
            field=models.CharField(
                choices=[
                    ("card", "Card"),
                    ("bank_account", "Bank Account"),
                    ("other", "Other"),
                ],
                default="card",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentmethod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("customer",),
                name="unique_default_per_customer",
            ),
        ),
    ]
