# Generated by Django 5.2.11 on 2026-08-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0074_merge_20260724_1500"),
        ("organizations", "0077_alter_paymentmethod_method_type_and_more"),
    ]

    operations = []
