# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


def consolidate_receipt_emails(apps, schema_editor):
    """Keep only the first receipt email per organization."""
    ReceiptEmail = apps.get_model("organizations", "ReceiptEmail")
    # Find orgs with multiple receipt emails
    from django.db.models import Count, Min

    dupes = (
        ReceiptEmail.objects.values("organization")
        .annotate(cnt=Count("id"), keep=Min("id"))
        .filter(cnt__gt=1)
    )
    for row in dupes:
        ReceiptEmail.objects.filter(
            organization_id=row["organization"]
        ).exclude(id=row["keep"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0077_charge_receipt_pdf"),
    ]

    operations = [
        # 1. Consolidate to one receipt email per org
        migrations.RunPython(
            consolidate_receipt_emails,
            migrations.RunPython.noop,
            elidable=True,
        ),
        # 2. Remove unique_together constraint
        migrations.AlterUniqueTogether(
            name="receiptemail",
            unique_together=set(),
        ),
        # 3. Change ForeignKey to OneToOneField
        migrations.AlterField(
            model_name="receiptemail",
            name="organization",
            field=models.OneToOneField(
                help_text=(
                    "The organization this billing email "
                    "corresponds to"
                ),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipt_email",
                to="organizations.organization",
                verbose_name="organization",
            ),
        ),
    ]
