# Generated by Django 5.2.12 on 2026-07-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0074_merge_20260724_1500"),
        ("organizations", "0078_receiptemail_to_onetoone"),
    ]

    operations = []
