# Generated by Django 5.2.11 on 2026-08-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0078_scoutpost_credit_pack"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="planprice",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="planprice",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Whether new subscriptions use this price.  Stripe Prices are immutable, so changing what a tier costs means superseding this row rather than editing it: the old row stays, inactive, still pointing at the Stripe Price its existing subscribers are billed against.",
                verbose_name="active",
            ),
        ),
        migrations.AddConstraint(
            model_name="planprice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("plan", "interval", "label"),
                name="unique_active_plan_price",
            ),
        ),
    ]
