# Generated by Django 5.2.12 on 2026-08-18 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0078_merge_20260818_1036"),
        ("organizations", "0079_merge_20260729_1307"),
    ]

    operations = []
