# Generated by Django 5.2.12 on 2026-08-26 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0079_planprice_active"),
        ("organizations", "0080_merge_20260818_1709"),
    ]

    operations = []
