# Generated by Django 5.2.12 on 2026-07-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0080_merge_20260818_1709"),
    ]

    operations = [
        migrations.AddField(
            model_name="entitlement",
            name="benefits",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Plain-language benefits granted by this entitlement. Refer to quantities by resource name instead of hard-coding them, e.g. \"{base_requests} free requests each month\", so that quantities from several entitlements can be summed into one benefit. When any of a plan's entitlements define benefits, they override the plan's own benefits list for display.",
                verbose_name="benefits",
            ),
        ),
    ]
