# Generated by Django 5.2.12 on 2026-08-26 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0080_merge_20260818_1709"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="product",
            field=models.CharField(
                blank=True,
                choices=[
                    ("muckrock", "MuckRock"),
                    ("documentcloud", "DocumentCloud"),
                    ("sunlight", "Sunlight"),
                    ("scoutpost", "Scoutpost"),
                ],
                default="",
                help_text="Which product this plan is marketed under, for grouping tiers on the plan page.  This is a display label, not a description of what the plan grants - most plans span more than one product (Sunlight tiers grant MuckRock and DocumentCloud entitlements but are still marketed as Sunlight).  Do NOT use this to decide whether a plan switch is an upgrade or an unrelated addition; compare the entitlement client sets instead.  Blank on legacy plans not yet mapped to a tier.",
                max_length=20,
                verbose_name="product",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="stripe_product_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The Product ID on stripe that this plan's Prices hang off",
                max_length=255,
                verbose_name="stripe product id",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="granted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff user who authorized the non-standard pricing.  Blank for ordinary self-serve subscriptions.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="granted_subscriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="granted by",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="granted_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Why this subscription received non-standard pricing (comped, or a partner coupon).  Blank for ordinary self-serve subscriptions.",
                verbose_name="granted reason",
            ),
        ),
        migrations.CreateModel(
            name="PlanPrice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_price_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The Price ID on stripe.  Blank for comped prices: those never create a Stripe subscription, so they have no Stripe counterpart to point at.  Uniqueness is enforced only on non-blank values.",
                        max_length=255,
                        verbose_name="stripe price id",
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("annual", "Annual"),
                            ("one_time", "One-time"),
                        ],
                        help_text="How often this price is billed",
                        max_length=20,
                        verbose_name="interval",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("nonprofit", "Nonprofit"),
                            ("comped", "Comped"),
                        ],
                        default="standard",
                        help_text="Ongoing structural rate class this price represents",
                        max_length=20,
                        verbose_name="label",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        blank=True,
                        default="",
                        help_text="Blank for list pricing - one such price per plan, interval and label.  Set to a short slug naming an individually negotiated deal (e.g. 'insideclimate'), which may sit above or below list: Stripe has no negative coupon, so a rate above list can only be expressed as a price of its own.  Coupons are for time-limited promotions.",
                        verbose_name="code",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        help_text="Amount in cents, matching Charge.amount and Stripe's unit_amount.  Note the legacy Plan.base_price is in whole dollars - the two coexist until that field is removed.",
                        verbose_name="amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="usd",
                        help_text="ISO 4217 currency code",
                        max_length=3,
                        verbose_name="currency",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether new subscriptions use this price.  Stripe Prices are immutable, so changing what a tier costs means superseding this row rather than editing it: the old row stays, inactive, still pointing at the Stripe Price its existing subscribers are billed against.",
                        verbose_name="active",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="The plan this price belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prices",
                        to="organizations.plan",
                        verbose_name="plan",
                    ),
                ),
            ],
            options={
                "ordering": ("plan", "interval", "label", "code"),
            },
        ),
        migrations.AddField(
            model_name="subscription",
            name="plan_price",
            field=models.ForeignKey(
                blank=True,
                help_text="The price this subscription is billed at.  Nullable until every subscription has been migrated off the legacy plan foreign key.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="organizations.planprice",
                verbose_name="plan price",
            ),
        ),
        migrations.AddConstraint(
            model_name="planprice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("stripe_price_id", ""), _negated=True),
                fields=("stripe_price_id",),
                name="unique_stripe_price_id_when_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="planprice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("plan", "interval", "label", "code"),
                name="unique_active_plan_price",
            ),
        ),
    ]
