# Generated by Django 5.2.12 on 2026-08-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0081_merge_0079_planprice_active_0080_merge_20260818_1709"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="planprice",
            options={"ordering": ("plan", "interval", "label", "code")},
        ),
        migrations.RemoveConstraint(
            model_name="planprice",
            name="unique_active_plan_price",
        ),
        migrations.AddField(
            model_name="planprice",
            name="code",
            field=models.SlugField(
                blank=True,
                default="",
                help_text="Blank for list pricing - one such price per plan, interval and label.  Set to a short slug naming an individually negotiated deal (e.g. 'insideclimate'), which may sit above or below list: Stripe has no negative coupon, so a rate above list can only be expressed as a price of its own.  Coupons are for time-limited promotions.",
                verbose_name="code",
            ),
        ),
        migrations.AddConstraint(
            model_name="planprice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("plan", "interval", "label", "code"),
                name="unique_active_plan_price",
            ),
        ),
    ]
