# Generated by Django 5.2.12 on 2026-09-09 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0081_entitlement_benefits"),
        ("organizations", "0082_plan_tiers_and_packs"),
    ]

    operations = []
