# Generated by Django 5.2.12 on 2026-08-26 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0083_rename_subscription_to_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionitem",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_items",
                to="organizations.organization",
                verbose_name="organization",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionitem",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_items",
                to="organizations.plan",
                verbose_name="plan",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionitem",
            name="plan_price",
            field=models.ForeignKey(
                blank=True,
                help_text="The price this subscription is billed at.  Nullable until every subscription has been migrated off the legacy plan foreign key.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscription_items",
                to="organizations.planprice",
                verbose_name="plan price",
            ),
        ),
    ]
