# Generated by Django 5.2.12 on 2026-09-14 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0082_organization_client_stats"),
        ("organizations", "0083_merge_20260909_1055"),
    ]

    operations = []
