# Generated by Django 5.2.12 on 2026-08-26 20:15

from django.db import migrations, models


def adopt_parent_cancellation(apps, schema_editor):
    """Give every line of a cancelled subscription its parent's cancellation.

    `0084` moved this pair off the line and onto the parent, which is where
    it belongs - one Stripe subscription, one cancellation.  The columns
    added just above bring it back at the line level, for the per-line
    cancellation this migration exists to support, and they arrive at their
    defaults: not cancelled, no date.

    Left that way, an organization part-way through a cancellation at deploy
    time would have a parent that says it is ending and lines that say they
    renew.  Billing would still be right - the sweep and Stripe both act on
    the parent - but the billing page reads the line, so the customer would
    be told their cancelled plan renews, and offered a button to cancel it
    again, for the whole window between the deploy and the period end.

    This is the same invariant `Subscription.push_cancellation_to_items`
    keeps at runtime.  The migration is just what establishes it.
    """
    Subscription = apps.get_model("organizations", "Subscription")

    for subscription in Subscription.objects.filter(cancelled=True):
        subscription.items.update(
            cancelled=True, cancel_at=subscription.cancel_at
        )


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0084_subscription_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionitem",
            name="cancel_at",
            field=models.DateField(
                blank=True,
                help_text="When this line is dropped from the Stripe subscription.  Taken from the subscription's current period end, because every line on a subscription shares one billing period.",
                null=True,
                verbose_name="cancel at",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionitem",
            name="cancelled",
            field=models.BooleanField(
                default=False,
                help_text="This line is scheduled to stop at the end of the current billing period.  It still bills and still grants access until then, mirroring how a cancelled subscription behaves.",
                verbose_name="cancelled",
            ),
        ),
        # Nothing to undo: reversing the two AddFields above drops the
        # columns this fills in.
        migrations.RunPython(
            adopt_parent_cancellation, migrations.RunPython.noop
        ),
    ]
