# Generated by Django 5.2.12 on 2026-08-26 18:10

import django.db.models.deletion
from django.db import migrations, models


def adopt_items_into_subscriptions(apps, schema_editor):
    """Create one Subscription per existing item and link them.

    Every organization holds exactly one subscription today - multi-plan
    support existed in the schema but was never used - so this is a
    straight one-to-one lift, not a grouping exercise.

    Interval and collection method are inferred from the plan: annual plans
    bill annually and are the only ones invoiced rather than charged.
    """
    SubscriptionItem = apps.get_model("organizations", "SubscriptionItem")
    Subscription = apps.get_model("organizations", "Subscription")
    Invoice = apps.get_model("organizations", "Invoice")

    for item in SubscriptionItem.objects.select_related("plan", "organization"):
        annual = bool(item.plan and item.plan.annual)
        subscription = Subscription.objects.create(
            organization=item.organization,
            subscription_id=item.legacy_subscription_id or "",
            interval="annual" if annual else "monthly",
            collection_method=(
                "send_invoice" if annual else "charge_automatically"
            ),
            cancelled=item.cancelled,
            cancel_at=item.cancel_at,
            stripe_status=item.stripe_status,
            current_period_end=item.current_period_end,
        )
        item.subscription = subscription
        item.save(update_fields=["subscription"])

        # Invoices billed this line; they now belong to its parent.
        Invoice.objects.filter(subscription=item).update(
            new_subscription=subscription
        )


def split_back_out(apps, schema_editor):
    """Copy subscription-level state back onto each item, then drop parents."""
    SubscriptionItem = apps.get_model("organizations", "SubscriptionItem")
    Subscription = apps.get_model("organizations", "Subscription")

    for item in SubscriptionItem.objects.select_related("subscription"):
        parent = item.subscription
        if parent is None:
            continue
        item.organization = parent.organization
        item.legacy_subscription_id = parent.subscription_id or None
        item.cancelled = parent.cancelled
        item.cancel_at = parent.cancel_at
        item.stripe_status = parent.stripe_status
        item.current_period_end = parent.current_period_end
        item.save()
    Subscription.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0084_subscriptionitem_related_names"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="plans",
        ),
        migrations.AddField(
            model_name="subscriptionitem",
            name="stripe_item_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The subscription item ID on stripe.  Blank for items that never reach Stripe, which is every comped one.",
                max_length=255,
                verbose_name="stripe item id",
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subscription_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The subscription ID on stripe.  Blank for subscriptions that never reach Stripe, which is every comped one.",
                        max_length=255,
                        verbose_name="subscription id",
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("annual", "Annual")],
                        default="monthly",
                        help_text="Billing interval shared by every item",
                        max_length=20,
                        verbose_name="interval",
                    ),
                ),
                (
                    "collection_method",
                    models.CharField(
                        choices=[
                            ("charge_automatically", "Charge automatically"),
                            ("send_invoice", "Send invoice"),
                        ],
                        default="charge_automatically",
                        help_text="How Stripe collects payment, shared by every item",
                        max_length=30,
                        verbose_name="collection method",
                    ),
                ),
                ("cancelled", models.BooleanField(default=False)),
                (
                    "cancel_at",
                    models.DateField(
                        blank=True,
                        help_text="Date when Stripe will terminate this subscription.  Set when cancel() is called.  Null for free subscriptions.",
                        null=True,
                        verbose_name="cancel at",
                    ),
                ),
                (
                    "stripe_status",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="organizations.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "plans",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Plans billed on this subscription",
                        related_name="subscriptions",
                        through="organizations.SubscriptionItem",
                        to="organizations.plan",
                        verbose_name="plans",
                    ),
                ),
            ],
            options={
                "ordering": ("organization", "interval"),
            },
        ),
        migrations.AlterUniqueTogether(
            name="subscriptionitem",
            unique_together=set(),
        ),
        # The FK below wants the column name `subscription_id`, which the old
        # CharField still occupies until it is dropped further down.  Rename
        # it out of the way rather than dropping it early - the data
        # migration still needs to read it.
        migrations.RenameField(
            model_name="subscriptionitem",
            old_name="subscription_id",
            new_name="legacy_subscription_id",
        ),
        migrations.AddField(
            model_name="subscriptionitem",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                help_text="The Stripe subscription this is a line on",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="organizations.subscription",
                verbose_name="subscription",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subscriptionitem",
            unique_together={("subscription", "plan")},
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("subscription_id", ""), _negated=True),
                fields=("subscription_id",),
                name="unique_stripe_subscription_id_when_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("organization", "interval", "collection_method"),
                name="unique_subscription_per_billing_shape",
            ),
        ),
        # Give every existing item a parent, carrying its Stripe linkage
        # across before the columns holding it are dropped below.
        migrations.AddField(
            model_name="invoice",
            name="new_subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="organizations.subscription",
            ),
        ),
        migrations.RunPython(adopt_items_into_subscriptions, split_back_out),
        migrations.RemoveField(
            model_name="invoice",
            name="subscription",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="new_subscription",
            new_name="subscription",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                help_text="The subscription this invoice is for, if applicable",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="organizations.subscription",
                verbose_name="subscription",
            ),
        ),
        migrations.RemoveField(
            model_name="subscriptionitem",
            name="cancel_at",
        ),
        migrations.RemoveField(
            model_name="subscriptionitem",
            name="cancelled",
        ),
        migrations.RemoveField(
            model_name="subscriptionitem",
            name="current_period_end",
        ),
        migrations.RemoveField(
            model_name="subscriptionitem",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="subscriptionitem",
            name="stripe_status",
        ),
        migrations.RemoveField(
            model_name="subscriptionitem",
            name="legacy_subscription_id",
        ),
    ]
