# Generated by Django 5.2.12 on 2026-08-26 18:10

from collections import defaultdict

import django.db.models.deletion
from django.db import migrations, models


def adopt_items_into_subscriptions(apps, schema_editor):
    """Give every item a parent, one per billing shape.

    Stripe requires every item on a subscription to share a billing interval
    and a collection method, which is what the new uniqueness constraint
    encodes: one Subscription per (organization, interval, collection
    method).  Items agreeing on all three belong on the same parent.

    In practice this is a one-to-one lift - every organization holds exactly
    one subscription today, multi-plan support having existed in the schema
    without ever being used.  It is written as a grouping anyway: a parent
    per item would meet that constraint as an opaque IntegrityError, halfway
    through a deploy, if a second line of the same shape appeared between
    now and then.

    Interval and collection method are inferred from the plan: annual plans
    bill annually and are the only ones invoiced rather than charged.
    """
    SubscriptionItem = apps.get_model("organizations", "SubscriptionItem")
    Subscription = apps.get_model("organizations", "Subscription")
    Invoice = apps.get_model("organizations", "Invoice")

    groups = defaultdict(list)
    for item in SubscriptionItem.objects.select_related("plan").order_by("pk"):
        annual = bool(item.plan and item.plan.annual)
        interval = "annual" if annual else "monthly"
        collection_method = "send_invoice" if annual else "charge_automatically"
        groups[(item.organization_id, interval, collection_method)].append(item)

    for (organization_id, interval, collection_method), items in groups.items():
        stripe_ids = {
            item.legacy_subscription_id for item in items
            if item.legacy_subscription_id
        }
        if len(stripe_ids) > 1:
            # Two Stripe subscriptions of the same shape for one
            # organization.  They cannot share a parent - the row holds one
            # Stripe id, so the other would still be billing with nothing
            # naming it - and the constraint leaves no room for two parents.
            # Refuse, naming both, rather than pick one and lose the other.
            raise RuntimeError(
                "Organization %s holds more than one %s/%s Stripe "
                "subscription (%s).  Consolidate them before migrating."
                % (
                    organization_id,
                    interval,
                    collection_method,
                    ", ".join(sorted(stripe_ids)),
                )
            )

        # A parent stops only once every line on it has stopped; one
        # cancelled line among several is that line's own business.
        cancelled = all(item.cancelled for item in items)
        cancel_ats = [item.cancel_at for item in items if item.cancel_at]
        # The Stripe-facing fields describe a single subscription, so they
        # come from the line naming it - identical across the group, by the
        # check above.
        source = next(
            (item for item in items if item.legacy_subscription_id), items[0]
        )
        subscription = Subscription.objects.create(
            organization_id=organization_id,
            subscription_id=source.legacy_subscription_id or "",
            interval=interval,
            collection_method=collection_method,
            cancelled=cancelled,
            cancel_at=max(cancel_ats) if cancelled and cancel_ats else None,
            stripe_status=source.stripe_status,
            current_period_end=source.current_period_end,
        )
        SubscriptionItem.objects.filter(pk__in=[item.pk for item in items]).update(
            subscription=subscription
        )

        # Invoices billed these lines; they now belong to the parent.
        Invoice.objects.filter(subscription__in=items).update(
            new_subscription=subscription
        )


def split_back_out(apps, schema_editor):
    """Copy subscription-level state back onto each item, then drop parents.

    This does not make the migration reversible on a database with rows in
    it, and is not meant to: reversing the operations below re-adds
    `organization_id` as NOT NULL before this function can fill it in, so
    Postgres rejects the column before the data ever gets here.  Rolling this
    deploy back means restoring from a backup.  What follows documents the
    shape of the reverse, and works on an empty database.

    `legacy_subscription_id` is unique, so a Stripe id can go back onto only
    one line.  A parent carrying several lines is precisely the shape the old
    schema could not hold - it is what the split exists to make possible - so
    the id returns to the oldest line and the rest name nothing.  Rolling
    back a deploy that had already built such a subscription needs those
    extra lines dealt with by hand, which beats refusing to roll back.
    """
    SubscriptionItem = apps.get_model("organizations", "SubscriptionItem")
    Subscription = apps.get_model("organizations", "Subscription")

    for parent in Subscription.objects.all():
        for index, item in enumerate(parent.items.order_by("pk")):
            item.organization_id = parent.organization_id
            item.legacy_subscription_id = (
                (parent.subscription_id or None) if index == 0 else None
            )
            item.cancelled = parent.cancelled
            item.cancel_at = parent.cancel_at
            item.stripe_status = parent.stripe_status
            item.current_period_end = parent.current_period_end
            item.save()
    Subscription.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0084_subscriptionitem_related_names"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="plans",
        ),
        migrations.AddField(
            model_name="subscriptionitem",
            name="stripe_item_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The subscription item ID on stripe.  Blank for items that never reach Stripe, which is every comped one.",
                max_length=255,
                verbose_name="stripe item id",
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subscription_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The subscription ID on stripe.  Blank for subscriptions that never reach Stripe, which is every comped one.",
                        max_length=255,
                        verbose_name="subscription id",
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("annual", "Annual")],
                        default="monthly",
                        help_text="Billing interval shared by every item",
                        max_length=20,
                        verbose_name="interval",
                    ),
                ),
                (
                    "collection_method",
                    models.CharField(
                        choices=[
                            ("charge_automatically", "Charge automatically"),
                            ("send_invoice", "Send invoice"),
                        ],
                        default="charge_automatically",
                        help_text="How Stripe collects payment, shared by every item",
                        max_length=30,
                        verbose_name="collection method",
                    ),
                ),
                ("cancelled", models.BooleanField(default=False)),
                (
                    "cancel_at",
                    models.DateField(
                        blank=True,
                        help_text="Date when Stripe will terminate this subscription.  Set when cancel() is called.  Null for free subscriptions.",
                        null=True,
                        verbose_name="cancel at",
                    ),
                ),
                (
                    "stripe_status",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="organizations.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "plans",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Plans billed on this subscription",
                        related_name="subscriptions",
                        through="organizations.SubscriptionItem",
                        to="organizations.plan",
                        verbose_name="plans",
                    ),
                ),
            ],
            options={
                "ordering": ("organization", "interval"),
            },
        ),
        migrations.AlterUniqueTogether(
            name="subscriptionitem",
            unique_together=set(),
        ),
        # The FK below wants the column name `subscription_id`, which the old
        # CharField still occupies until it is dropped further down.  Rename
        # it out of the way rather than dropping it early - the data
        # migration still needs to read it.
        migrations.RenameField(
            model_name="subscriptionitem",
            old_name="subscription_id",
            new_name="legacy_subscription_id",
        ),
        migrations.AddField(
            model_name="subscriptionitem",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                help_text="The Stripe subscription this is a line on",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="organizations.subscription",
                verbose_name="subscription",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subscriptionitem",
            unique_together={("subscription", "plan")},
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("subscription_id", ""), _negated=True),
                fields=("subscription_id",),
                name="unique_stripe_subscription_id_when_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("organization", "interval", "collection_method"),
                name="unique_subscription_per_billing_shape",
            ),
        ),
        # Give every existing item a parent, carrying its Stripe linkage
        # across before the columns holding it are dropped below.
        migrations.AddField(
            model_name="invoice",
            name="new_subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="organizations.subscription",
            ),
        ),
        migrations.RunPython(adopt_items_into_subscriptions, split_back_out),
        migrations.RemoveField(
            model_name="invoice",
            name="subscription",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="new_subscription",
            new_name="subscription",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                help_text="The subscription this invoice is for, if applicable",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="organizations.subscription",
                verbose_name="subscription",
            ),
        ),
        migrations.RemoveField(
            model_name="subscriptionitem",
            name="cancel_at",
        ),
        migrations.RemoveField(
            model_name="subscriptionitem",
            name="cancelled",
        ),
        migrations.RemoveField(
            model_name="subscriptionitem",
            name="current_period_end",
        ),
        migrations.RemoveField(
            model_name="subscriptionitem",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="subscriptionitem",
            name="stripe_status",
        ),
        migrations.RemoveField(
            model_name="subscriptionitem",
            name="legacy_subscription_id",
        ),
    ]
