# Generated by Django 5.2.12 on 2026-09-18 12:00

from django.db import migrations


class Migration(migrations.Migration):
    """Join the split migrations to master's graph.

    #813 landed between this branch being cut and #781 merging, bringing
    `0082_organization_client_stats` and its own merge node.  A merge
    migration rather than re-parenting `0083_rename` onto that node: the
    rename is already applied on every review app and on staging, and
    changing an applied migration's dependencies makes Django refuse to
    migrate that database at all.  Adding a node never does.
    """

    dependencies = [
        ("organizations", "0084_merge_20260914_1323"),
        ("organizations", "0084_subscription_parent"),
    ]

    operations = []
