# Generated by Django 5.2.12 on 2026-08-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0085_subscription_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionitem",
            name="cancel_at",
            field=models.DateField(
                blank=True,
                help_text="When this line is dropped from the Stripe subscription.  Taken from the subscription's current period end, because every line on a subscription shares one billing period.",
                null=True,
                verbose_name="cancel at",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionitem",
            name="cancelled",
            field=models.BooleanField(
                default=False,
                help_text="This line is scheduled to stop at the end of the current billing period.  It still bills and still grants access until then, mirroring how a cancelled subscription behaves.",
                verbose_name="cancelled",
            ),
        ),
    ]
