# Generated by Django 5.2.12 on 2026-09-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0085_subscription_item_cancellation"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="archived",
            field=models.BooleanField(
                default=False,
                help_text="Retired: nobody is on it and it can no longer be bought.  The row is kept because the change log references it - deleting it would destroy the history of who used to be on what.",
                verbose_name="archived",
            ),
        ),
    ]
