# Generated by Django 5.2.12 on 2026-09-24 13:27

from collections import Counter

from django.db import migrations, models


def kind_of(plan):
    if plan.base_price == 0 and plan.price_per_user == 0:
        return "free"
    if not plan.auto_renew:
        return "one_off"
    return "renewing"


def classify(apps, schema_editor):
    """Give each subscription the kind its lines make it.

    Refuses rows whose lines disagree, and organizations with more than one
    free row, rather than guess where each line belongs.
    """
    Subscription = apps.get_model("organizations", "Subscription")
    problems = []
    free_rows = Counter()
    for subscription in Subscription.objects.prefetch_related("items__plan"):
        plans = [item.plan for item in subscription.items.all() if item.plan]
        kinds = {kind_of(plan) for plan in plans}
        if len(kinds) > 1 or ("one_off" in kinds and len(plans) > 1):
            problems.append(
                f"subscription {subscription.pk} (organization "
                f"{subscription.organization_id}) mixes "
                + ", ".join(sorted(plan.name for plan in plans))
            )
            continue
        kind = kinds.pop() if kinds else "renewing"
        if kind == "free":
            free_rows[subscription.organization_id] += 1
        if kind != "renewing":
            Subscription.objects.filter(pk=subscription.pk).update(kind=kind)
    problems += [
        f"organization {org} has {count} free subscriptions"
        for org, count in free_rows.items()
        if count > 1
    ]
    if problems:
        raise RuntimeError(
            "Split these by hand before migrating:\n  " + "\n  ".join(problems)
        )


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0085_merge_20260918_1200"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subscription",
            name="unique_subscription_per_billing_shape",
        ),
        migrations.AddField(
            model_name="subscription",
            name="kind",
            field=models.CharField(
                choices=[
                    ("renewing", "Renewing"),
                    ("one_off", "One-off"),
                    ("free", "Free"),
                ],
                default="renewing",
                help_text="Renewing paid plans share a subscription per billing shape, a one-off purchase gets its own, and free plans never reach Stripe.",
                max_length=20,
                verbose_name="kind",
            ),
        ),
        migrations.RunPython(classify, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cancelled", False), ("kind", "renewing")),
                fields=("organization", "interval", "collection_method"),
                name="unique_live_renewing_subscription_per_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "free")),
                fields=("organization",),
                name="unique_free_subscription_per_organization",
            ),
        ),
    ]
