# Generated by Django 5.2.12 on 2026-09-24 13:27

from collections import defaultdict

from django.db import migrations, models


def kind_of(plan):
    if plan.base_price == 0 and plan.price_per_user == 0:
        return "free"
    if not plan.auto_renew:
        return "one_off"
    return "renewing"


def classify(apps, schema_editor):
    """Give each subscription the kind its lines make it.

    Free lines never reach Stripe, so each organization's are gathered onto one
    free row.  A one-off sharing a row with other paid lines would need a live
    Stripe subscription split, so that is refused rather than guessed.
    """
    Invoice = apps.get_model("organizations", "Invoice")
    Subscription = apps.get_model("organizations", "Subscription")
    SubscriptionItem = apps.get_model("organizations", "SubscriptionItem")

    problems = []
    stray = defaultdict(list)
    free_rows = defaultdict(list)
    for subscription in Subscription.objects.prefetch_related("items__plan").order_by(
        "pk"
    ):
        lines = [item for item in subscription.items.all() if item.plan]
        free = [item for item in lines if kind_of(item.plan) == "free"]
        paid = [item for item in lines if kind_of(item.plan) != "free"]
        if len(paid) > 1 and any(kind_of(item.plan) == "one_off" for item in paid):
            problems.append(
                f"subscription {subscription.pk} (organization "
                f"{subscription.organization_id}) has a one-off beside "
                + ", ".join(sorted(item.plan.name for item in paid))
            )
            continue
        if paid:
            kind = kind_of(paid[0].plan)
            if free:
                stray[subscription.organization_id].extend(free)
        elif free:
            kind = "free"
            free_rows[subscription.organization_id].append(subscription)
        else:
            continue
        if kind != "renewing":
            Subscription.objects.filter(pk=subscription.pk).update(kind=kind)
    if problems:
        raise RuntimeError(
            "Split these by hand before migrating:\n  " + "\n  ".join(problems)
        )

    for organization_id in set(stray) | {
        org for org, rows in free_rows.items() if len(rows) > 1
    }:
        rows = free_rows.get(organization_id, [])
        target = (
            rows[0]
            if rows
            else Subscription.objects.create(
                organization_id=organization_id, kind="free"
            )
        )
        moving = stray.get(organization_id, []) + [
            item for row in rows[1:] for item in row.items.all()
        ]
        held = set(target.items.values_list("plan_id", flat=True))
        for item in moving:
            if item.plan_id in held:
                item.delete()
                continue
            SubscriptionItem.objects.filter(pk=item.pk).update(
                subscription=target, stripe_item_id=""
            )
            held.add(item.plan_id)
        for row in rows[1:]:
            Invoice.objects.filter(subscription=row).update(subscription=target)
            row.delete()

    # Postgres refuses to index a table with trigger events still pending, and
    # the constraints after this build indexes on it.
    schema_editor.execute("SET CONSTRAINTS ALL IMMEDIATE")


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0085_merge_20260918_1200"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subscription",
            name="unique_subscription_per_billing_shape",
        ),
        migrations.AddField(
            model_name="subscription",
            name="kind",
            field=models.CharField(
                choices=[
                    ("renewing", "Renewing"),
                    ("one_off", "One-off"),
                    ("free", "Free"),
                ],
                default="renewing",
                help_text="Renewing paid plans share a subscription per billing shape, a one-off purchase gets its own, and free plans never reach Stripe.",
                max_length=20,
                verbose_name="kind",
            ),
        ),
        migrations.RunPython(classify, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cancelled", False), ("kind", "renewing")),
                fields=("organization", "interval", "collection_method"),
                name="unique_live_renewing_subscription_per_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "free")),
                fields=("organization",),
                name="unique_free_subscription_per_organization",
            ),
        ),
    ]
