# Generated by Django 5.2.12 on 2026-09-18 12:10

from django.db import migrations


class Migration(migrations.Migration):
    """Join per-line cancellation to the merged graph below it.

    `0085_subscription_item_cancellation` was written against
    `0084_subscription_parent` alone.  The branch beneath this one gained
    a merge node joining that to master's graph, which left this
    migration and that merge node as two leaves.  Another merge, not a
    re-parent: `0085_subscription_item_cancellation` is applied on this
    branch's review app, and changing an applied migration's
    dependencies makes Django refuse the whole database.
    """

    dependencies = [
        ("organizations", "0085_merge_20260918_1200"),
        ("organizations", "0085_subscription_item_cancellation"),
    ]

    operations = []
