# Generated by Django 5.2.12 on 2026-09-30 12:00

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0085_merge_20260918_1200"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entitlement",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=True,
                help_text="A slug to identify the entitlement",
                populate_from="name",
                unique_with=("client",),
                verbose_name="slug",
            ),
        ),
    ]
