# Generated by Django 5.2.12 on 2026-10-07 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0086_entitlement_slug_editable"),
        ("organizations", "0086_subscription_kind"),
    ]

    operations = []
