# Generated by Django 5.2.12 on 2026-09-18 12:20

from django.db import migrations


class Migration(migrations.Migration):
    """Join plan archiving to the merged graph below it.

    `0086_plan_archived` was written against
    `0085_subscription_item_cancellation` alone; the branches beneath
    gained merge nodes joining the stack to master's graph.  See
    `0085_merge_20260918_1200` for why these are merges and not
    re-parents.
    """

    dependencies = [
        ("organizations", "0086_merge_20260918_1210"),
        ("organizations", "0086_plan_archived"),
    ]

    operations = []
