# Generated by Django 2.0.6 on 2018-12-10 20:08

from django.db import migrations, models
import django.db.models.deletion
import squarelet.oidc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oidc_provider', '0025_user_field_codetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.URLField(blank=True)),
                ('secret_key', models.CharField(default=squarelet.oidc.models.make_secret_key, max_length=24)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oidc_provider.Client')),
            ],
        ),
    ]
