# Generated by Django 2.0.6 on 2019-01-17 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('oidc', '0001_initial'), ('oidc', '0002_remove_clientprofile_secret_key')]

    initial = True

    dependencies = [
        ('oidc_provider', '0025_user_field_codetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.URLField(blank=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oidc_provider.Client')),
            ],
        ),
    ]
