# Generated by Django 2.1.7 on 2019-09-19 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oidc', '0001_squashed_0002_remove_clientprofile_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='client',
            field=models.OneToOneField(help_text='OIDC provider client this profile provides extra data for', on_delete=django.db.models.deletion.CASCADE, to='oidc_provider.Client', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='URL to send webhook notifications to for this client', verbose_name='webhook URL'),
        ),
    ]
