# Generated by Django 2.1.7 on 2020-04-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc', '0002_auto_20190919_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='source',
            field=models.CharField(choices=[('muckrock', 'MuckRock'), ('presspass', 'PressPass')], default='muckrock', max_length=10, verbose_name='source'),
        ),
    ]
