# Generated by Django 2.1.7 on 2020-04-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc', '0003_clientprofile_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='source',
            field=models.CharField(choices=[('muckrock', 'MuckRock'), ('presspass', 'PressPass')], default='muckrock', help_text='Which application did this client originate from?', max_length=10, verbose_name='source'),
        ),
    ]
