# Generated by Django 5.2.12 on 2026-07-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oidc", "0004_auto_20200407_1248"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="checks_verification",
            field=models.BooleanField(
                default=False,
                help_text="Whether this client gates features behind verification. When enabled, unverified users are shown an informational notice during authorization.",
                verbose_name="checks verification",
            ),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="verification_notice",
            field=models.TextField(
                blank=True,
                help_text="Explanation shown to unverified users describing what this client limits to verified journalists. Markdown formatting supported. Only used when 'checks verification' is enabled.",
                verbose_name="verification notice",
            ),
        ),
    ]
