# Generated by Django 4.2 on 2025-01-27 23:07

from django.db import migrations, models
import squarelet.services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly name for the service",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the service", max_length=255
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        help_text="Icon for the service",
                        upload_to=squarelet.services.models.service_file_path,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Short description of the service"),
                ),
                (
                    "provider_name",
                    models.CharField(
                        help_text="Name of the service provider/maintainer",
                        max_length=255,
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        blank=True,
                        help_text="Base URL for the service (e.g. https://www.muckrock.com)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
