# Generated by Django 2.1.7 on 2019-03-06 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.IntegerField()),
                ('total_users_excluding_agencies', models.IntegerField()),
                ('total_users_pro', models.IntegerField()),
                ('total_users_org', models.IntegerField()),
                ('total_orgs', models.IntegerField()),
                ('pro_users', models.ManyToManyField(related_name='_statistics_pro_users_+', to=settings.AUTH_USER_MODEL)),
                ('users_today', models.ManyToManyField(related_name='_statistics_users_today_+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'statistics',
                'ordering': ['-date'],
            },
        ),
    ]
