# Generated by Django 2.1.7 on 2019-09-19 20:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='date',
            field=models.DateField(help_text='The date these statistics were taken', unique=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='pro_users',
            field=models.ManyToManyField(help_text='The users who had a professional account on this date', related_name='_statistics_pro_users_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='total_orgs',
            field=models.IntegerField(help_text='The total number of organizations in the database excluding free individual organizations'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='total_users',
            field=models.IntegerField(help_text='The total number of users in the database'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='total_users_excluding_agencies',
            field=models.IntegerField(help_text='The total number of users in the database excluding agency users'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='total_users_org',
            field=models.IntegerField(help_text='Total users who have an organizational subscription'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='total_users_pro',
            field=models.IntegerField(help_text='Total users who have a professional subscription'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='users_today',
            field=models.ManyToManyField(help_text='Users who logged in on this date', related_name='_statistics_users_today_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
