# Generated by Django 2.1.7 on 2020-03-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0002_auto_20190919_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='verified_orgs',
            field=models.IntegerField(default=0, help_text='The number of organizations which are verified journalists'),
            preserve_default=False,
        ),
    ]
