# Generated by Django 4.2 on 2023-06-26 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("statistics", "0003_statistics_verified_orgs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statistics",
            name="pro_users",
            field=models.ManyToManyField(
                help_text="The users who had a professional account on this date",
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="statistics",
            name="users_today",
            field=models.ManyToManyField(
                help_text="Users who logged in on this date",
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
