# Generated by Django 4.2 on 2025-05-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistics", "0004_alter_statistics_pro_users_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statistics",
            name="total_users_mfa",
            field=models.IntegerField(
                default=0, help_text="Total users who have enabled MFA"
            ),
            preserve_default=False,
        ),
    ]
