name: Deploy static assets

on:
  push:
    branches: [master]
  pull_request:

env:
  DJANGO_AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  DJANGO_AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  DJANGO_AWS_STORAGE_BUCKET_NAME: ${{github.ref == 'refs/heads/master' && secrets.DJANGO_AWS_STORAGE_BUCKET_NAME || secrets.DJANGO_AWS_STORAGE_BUCKET_NAME_STAGING}}
  DJANGO_ADMIN_URL: ${{secrets.DJANGO_ADMIN_URL}}
  DJANGO_SECRET_KEY: ${{secrets.DJANGO_SECRET_KEY}}
  DJANGO_SETTINGS_MODULE: config.settings.production
  MUCKROCK_TOKEN: token
  STRIPE_SECRET_KEY: ${{secrets.STRIPE_SECRET_KEY}}
  STRIPE_PUB_KEY: ${{secrets.STRIPE_PUB_KEY}}
  STRIPE_WEBHOOK_SECRET: ${{secrets.STRIPE_WEBHOOK_SECRET}}
  AIRTABLE_ACCESS_TOKEN: ${{secrets.AIRTABLE_ACCESS_TOKEN}}
  AIRTABLE_ERH_BASE_ID: ${{secrets.AIRTABLE_ERH_BASE_ID}}
  AIRTABLE_ERH_TABLE_ID: ${{secrets.AIRTABLE_ERH_TABLE_ID}}
  MAILGUN_ACCESS_KEY: ""
  USE_DOCKER: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    # we just need a database connection to run ./manage.py
    # this isn't a real database
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: squarelet
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "npm"

      - name: "Install node dependencies"
        run: npm ci --include dev

      - name: Install python dependencies
        run: |
          pip install -r requirements/production.txt

      - name: Build
        run: npm run build

      - name: Collect static
        run: python manage.py collectstatic --noinput
        env:
          # use the credentials for the service containers
          DATABASE_URL: postgresql://test:postgres@localhost:5432/squarelet
          REDIS_URL: redis://localhost:6379/0
